id: brandfolder-open-redirect
info:
  name: WordPress Brandfolder Plugin Open Redirect
  author:
  - l0ne1y
  tags:
  - wordpress
  - wp-plugin
  - lfi
  - rfi
  description: |-
    Wordpress Plugin Brandfolder has URL redirection vulnerability
    A vulnerability in WordPress Brandfolder allows remote attackers to inject arbitrary URLs via the "wp_abspath" parameter to the "callback.php" endpoint, which will redirect the victim to that endpoint.
  reference:
  - https://www.exploit-db.com/exploits/39591
  severity: low
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/zh-cn/install-plugins/

    Temporary fix:
    1. The code fixes the jump address and does not allow users to control variables.
    2. The redirect target address adopts a whitelist mapping mechanism and only redirects to legal URLs.
    3. Verify the target address of the jump reasonably and fully, and inform the user of the risk of jump if it is not your own address.
requests:
- matchers:
  - type: regex
    part: header
    regex:
    - (?m)^(?:Location\s*?:\s*?)(?:https?://|//)?(?:[a-zA-Z0-9\-_\.@]*)example\.com.*$
  path:
  - '{{BaseURL}}/wp-content/plugins/brandfolder/callback.php?wp_abspath=https://example.com/'
  method: GET
