id: CNVD-2018-25692
info:
  name: WordPress Total-Child-Theme-Master Themes 1.0 Arbitrary File Download Disclosure
  author:
  - l0ne1y
  description: |-
    WordPress Theme Total-Child-Theme-Master Arbitrary File Download Vulnerability
    WordPress is a blog platform developed by the WordPress Software Foundation using the PHP language. The platform supports the establishment of personal blog websites on PHP and MySQL servers.

    WordPress Total-Child-Theme-Master Themes has an arbitrary file download vulnerability. An attacker could exploit the vulnerability to download arbitrary files.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: http://www.wordpress.org

    Temporary fix:
    1. Filter \".\" so that users cannot go back to the upper directory in the URL.
    2. Regular matching strictly determines the format of user input parameters, hard-codes or uniformly encodes the file name parameters passed by the user, performs whitelist control on file types, and rejects parameters containing malicious characters or null characters.
    3. Prohibit the system from providing directory traversal services, such as: php.ini configures open_basedir to limit file access scope.
    4. Save the file path to the database and let the user submit the file corresponding to the ID to download the file.
    5. Verify permissions before users download files.
requests:
- matchers:
  - type: dsl
    dsl:
    - 'status_code==200 && contains(body,"Content-Type: application/zip")'
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/themes/total-child-theme-master/aa-backup-single.zip'
  method: GET
