id: CNVD-2019-07550
info:
  name: wordpress_bigchrome theme redirect
  author:
  - l0ne1y
  description: |-
    WordPress Theme BigChrome Opens URL Redirect Vulnerability
    WordPress is a blog platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers.

    WordPress BigChrome Themes has an open redirect vulnerability that could be exploited by attackers to conduct phishing scams and steal user credentials.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/

    Temporary fix:
    1. The code fixes the jump address and does not allow users to control variables.
    2. The redirect target address adopts a whitelist mapping mechanism and only redirects to legal URLs.
    3. Verify the target address of the jump reasonably and fully, and inform the user of the risk of jump if it is not your own address.
requests:
- matchers:
  - type: dsl
    dsl:
    - 'contains(body,"百度一下，你就知道") '
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/themes/bigchrome/inc/go.php?url=https://www.baidu.com'
  method: GET
  redirects: true
