id: CNVD-2019-08493
info:
  name: wordpress_ait-themesllub plugin redirect vulnerability
  author:
  - l0ne1y
  description: |-
    WordPress Theme Ait-ThemesClub TemplatePreview URL Redirect Vulnerability
    WordPress is a blog platform developed by the WordPress Software Foundation using the PHP language. The platform supports the establishment of personal blog websites on PHP and MySQL servers.

    There is a security vulnerability in WordPress Ait-ThemesClub TemplatePreview. An attacker could exploit the vulnerability to successfully launch a phishing scam and steal user credentials.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: http://www.ait-themes.club

    Temporary fix:
    1. The code fixes the jump address and does not allow users to control variables.
    2. The redirect target address adopts a whitelist mapping mechanism and only redirects to legal URLs.
    3. Verify the target address of the jump reasonably and fully, and inform the user of the risk of jump if it is not your own address.
requests:
- matchers:
  - type: dsl
    dsl:
    - contains(body,"百度一下，你就知道")
  matchers-condition: and
  path:
  - '{{BaseURL}}/template-preview.php?url=aHR0cHM6Ly93d3cuYmFpZHUuY29t'
  method: GET
  redirects: true
