id: WordPress-Ad_Buttons_Plugins-DatabaseDownload
info:
  name: WordPress Ad Buttons Plugins 3.1 Database download vulnerability
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Ad Buttons 3.1 Database Backup File Leak Vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers.

    Database information leakage vulnerability exists in WordPress ad-buttons plugin version 3.1
  severity: high
  remediation: "Official repair plan:\\n1. It is recommended that users go to the official website to obtain the latest patch or the latest version of the program: wordpress.org/plugins/ad-buttons/\n\\n\\nTemporary fixes:\\n1. Remove sensitive information involved in pages, cookies or caches or delete leaked information pages\\n2. Encrypt and store sensitive information and do not send it to the front end unless necessary\\n3. Encrypted transmission is required when sending sensitive information, and desensitization is required if necessary\\n4. It is prohibited to use self-developed encryption algorithms and must use public, secure standard encryption algorithms. \\n5. It is forbidden to record plain text sensitive data in the log: It is forbidden to record plain text sensitive data in the log (such as password, session ID jsessionid, etc.).\nPrevent the leakage of sensitive information. \\n6. Disable caching of Web pages containing sensitive data: Web pages containing sensitive data should be prohibited from caching\\n to prevent leakage of sensitive information or mutual exchange of user data through proxy servers. \\n7. Perform strict permission authentication for sensitive data or page request interfaces that must be sent."
requests:
- matchers:
  - type: status
    status:
    - 200
  - type: word
    words:
    - INSERT INTO
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/ad-buttons/ip2n_ip-1.sql'
  method: GET
