id: Wordpress-Ithemes_BackupBuddy_Amazon_WP-S3_Plugins-DatabaseDownload
info:
  name: WordPress Ithemes-BackupBuddy Amazon WP-S3 Plugins 2.9 Database download vulnerability
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Ithemes BackupBuddy Amazon WP-S3 database file information leakage vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers.

    A database information disclosure vulnerability exists in WordPress Ithemes-BackupBuddy Amazon WP-S3 Plugins version 2.9.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/

    Temporary fix:
    1. Remove sensitive information involved in pages, cookies or caches or delete pages that reveal information.
    2. Encrypt and store sensitive information and do not send it to the front end unless necessary.
    3. When sending sensitive information, it must be encrypted and desensitized if necessary.
    4. It is prohibited to use self-developed encryption algorithms. Public and secure standard encryption algorithms must be used.
    5. It is prohibited to record plain text sensitive data in logs: It is prohibited to record plain text sensitive data (such as oral
    command, session ID jsessionid, etc.) to prevent the leakage of sensitive information.
    6. Disable caching of Web pages containing sensitive data: Web pages containing sensitive data should be prohibited from caching.
    storage to prevent the leakage of sensitive information or the exchange of user data through proxy servers.
    7. Perform strict permission authentication for sensitive data or page request interfaces that must be sent.
requests:
- matchers:
  - type: status
    status:
    - 200
  - type: regex
    regex:
    - DROP TABLE
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/uploads/wp-s3-database-backup.sql'
  method: GET
