id: wordpress-total-upkeep-backup-download
info:
  name: WordPress Total Upkeep Database and Files Backup Download
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Total Upkeep Database and File Backup Leak Vulnerability
    WordPress is a blog platform developed by the WordPress Software Foundation using the PHP language. The platform supports the establishment of personal blog websites on PHP and MySQL servers. oEmbed discovery is one of the oEmbed search plug-ins.

    WordPress Total Upkeep is vulnerable to a database and file backup leak vulnerability.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com

    Temporary fix:
    1. Remove sensitive information involved in pages, cookies or caches or delete pages that reveal information.
    2. Encrypt and store sensitive information and do not send it to the front end unless necessary.
    3. When sending sensitive information, it must be encrypted and desensitized if necessary.
    4. It is prohibited to use self-developed encryption algorithms. Public and secure standard encryption algorithms must be used.
    5. It is prohibited to record plain text sensitive data in logs: It is prohibited to record plain text sensitive data (such as oral
    command, session ID jsessionid, etc.) to prevent the leakage of sensitive information.
    6. Disable caching of Web pages containing sensitive data: Web pages containing sensitive data should be prohibited from caching.
    storage to prevent the leakage of sensitive information or the exchange of user data through proxy servers.
    7. Perform strict permission authentication for sensitive data or page request interfaces that must be sent
requests:
- matchers:
  - type: word
    part: header
    words:
    - application/json
  - type: word
    condition: and
    part: body
    words:
    - '"filepath"'
    - /wp-content/boldgrid_backup_
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/boldgrid-backup/cron/restore-info.json'
  method: GET
