id: wordpress-db-repair
info:
  name: Wordpress DB Repair Exposed
  author:
  - l0ne1y
  tags:
  - wordpress
  - config
  - fpd
  description: |-
    WordPress database repair tool repair.php unauthorized access vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. repair.php is a database repair tool, designed to reset and recover when there is a database problem.
  severity: low
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/

    Temporary fix:
    1. Repair.php is prohibited from being directly exposed to the Internet. Internal systems need to be accessed through VPN and other relatively secure access methods.
    2. Repair.php turns on identity authentication and selects the corresponding method (authentication user, username and password) according to the situation.
    3. Restrict IP access and bind fixed IP to access the backend management system.
requests:
- matchers:
  - type: word
    words:
    - <title>WordPress
  - type: status
    status:
    - 200
  - type: word
    condition: and
    negative: true
    words:
    - define
    - WP_ALLOW_REPAIR
    - "true"
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-admin/maint/repair.php'
  method: GET
