id: Wordpress-497-InfoDisclosure
info:
  name: wordpress_4.9.7_Information leakage
  author:
  - l0ne1y
  description: |-
    WordPress 4.9.7 certificates information disclosure vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers.

    There is a certificate information leak vulnerability in WordPress version 4.9.7.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org

    Temporary fix:
    1. Remove sensitive information involved in pages, cookies or caches or delete pages that reveal information.
    2. Encrypt and store sensitive information and do not send it to the front end unless necessary.
    3. When sending sensitive information, it must be encrypted and desensitized if necessary.
    4. It is prohibited to use self-developed encryption algorithms. Public and secure standard encryption algorithms must be used.
    5. It is prohibited to record plain text sensitive data in logs: It is prohibited to record plain text sensitive data (such as oral
    command, session ID jsessionid, etc.) to prevent the leakage of sensitive information.
    6. Disable caching of Web pages containing sensitive data: Web pages containing sensitive data should be prohibited from caching.
    storage to prevent the leakage of sensitive information or the exchange of user data through proxy servers.
    7. Perform strict permission authentication for sensitive data or page request interfaces that must be sent.
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"Index of /wp-includes/certificates") && contains(body,"Last
      modified")
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-includes/certificates/'
  method: GET
