id: WordPress-Begin_Themes-Redirection
info:
  name: WordPress Begin Themes Start-up Business ThemeForest Open Redirection Vulnerability
  author:
  - l0ne1y
  description: |-
    WordPress Theme Begin has URL redirection vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress theme is an open source theme of WordPress.

    There is an input validation error vulnerability in go.php of WordPress Begin Themes Start-up Business ThemeForest, causing users to be redirected to a URL address that it did not validate before.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/zh-cn/install-plugins/

    Temporary fix:
    1. The code fixes the jump address and does not allow users to control variables.
    2. The redirect target address adopts a whitelist mapping mechanism and only redirects to legal URLs.
    3. Verify the target address of the jump reasonably and fully, and inform the user of the risk of jump if it is not your own address.
requests:
- matchers:
  - type: status
    status:
    - 200
  - type: word
    words:
    - 百度一下，你就知道
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/themes/begin/inc/go.php?url=https://www.baidu.com'
  method: GET
  redirects: true
