id: wordpress-upload-data
info:
  name: wordpress-upload-data
  author:
  - l0ne1y
  description: |
    WordPress uploads directory data.txt information leakage vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers.
    The remote WordPress installation contained a file "data.txt" under the "/wp-content/uploads/" folder, which contained sensitive information.
  severity: medium
  remediation: |-
    1. Remove sensitive information involved in pages, cookies or caches or delete pages that reveal information.
    2. Encrypt and store sensitive information and do not send it to the front end unless necessary.
    3. When sending sensitive information, it must be encrypted and desensitized if necessary.
    4. It is prohibited to use self-developed encryption algorithms. Public and secure standard encryption algorithms must be used.
    5. It is prohibited to record plain text sensitive data in logs: It is prohibited to record plain text sensitive data (such as oral
    command, session ID jsessionid, etc.) to prevent the leakage of sensitive information.
    6. Disable caching of Web pages containing sensitive data: Web pages containing sensitive data should be prohibited from caching.
    storage to prevent the leakage of sensitive information or the exchange of user data through proxy servers.
    7. Perform strict permission authentication for sensitive data or page request interfaces that must be sent
requests:
- matchers:
  - type: word
    words:
    - 'admin:'
  - type: word
    part: header
    words:
    - text/plain
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/uploads/data.txt'
  method: GET
