id: Wordpress-Social_Warfare_Plugins-RCE
info:
  name: WordPress Social Warfare Plugin Remote Code Execution Vulnerability
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Social Warfare remote file inclusion vulnerability
    The WordPress Social Warfare Plugin remote code execution vulnerability affects versions of the Social Warfare Plugin prior to 3.5.3.



    The vulnerability is located in the eval() function in the social-warfare\lib\utilities\SWP_Database_Migration.php file, which can run the PHP code defined by the attacker in the "swp_url" GET parameter. This vulnerability allows an attacker to take over your entire WordPress site and manage all files and databases on your hosting account, achieving a full remote takeover of your entire server.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/social-warfare/advanced/

    Temporary fix:
    1. Use open_basedir configuration in PHP to restrict access to specified areas and truncate the path length.
    2. Filter. (dot)/(backslash)\\(backslash), encoding bypass
    3. Disable server remote file inclusion
    4. For the situation where the included file suffix is ​​restricted, the PHP version is less than 5.3, php.ini magic_quotes_gpc = off, and the addslashes function is not used for controllable parameters. If these three conditions are met, %00 truncation can be used.
    5. Question mark, pound sign, and space bypass (remote)
requests:
- matchers:
  - type: dsl
    dsl:
    - 'status_code==200 && contains(body,"username") '
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-admin/admin-post.php?swp_debug=load_options&swp_url={{BaseURL}}/wp-admin/index.php'
  method: GET
