id: wp-config-setup
info:
  name: WordPress Setup Configuration
  author:
  - l0ne1y
  description: |2-
     WordPress CONFIG misconfiguration leads to remote code execution vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.

    WordPress has lax access control, which allows attackers to access the setup-config to reset the database and then lose control of the website.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/

    1. The backend management system is prohibited from being directly exposed to the Internet, and internal systems must be accessed through VPN and other relatively secure access methods.
    2. Enable identity authentication on all pages of the backend management system, and select the corresponding method (authentication user, username and password) according to the situation.
    3. Restrict IP access and bind fixed IP to access the backend management system.
    4. Use a mature permission management framework, such as spring security.
requests:
- matchers:
  - type: word
    words:
    - Below you should enter your database connection details.
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-admin/setup-config.php?step=1'
  method: GET
