id: wp-debug-log
info:
  name: WordPress debug log
  author:
  - l0ne1y
  description: |-
    WordPress debug log debugging information leakage vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers.
    The WordPress debug log stores debugging information while WordPress is running. After leakage, attackers can easily discover server-related information.
  severity: low
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com

    Temporary fix:
    1. Remove sensitive information involved in pages, cookies or caches or delete pages that reveal information.
    2. Encrypt and store sensitive information and do not send it to the front end unless necessary.
    3. When sending sensitive information, it must be encrypted and desensitized if necessary.
    4. It is prohibited to use self-developed encryption algorithms. Public and secure standard encryption algorithms must be used.
    5. It is prohibited to record plain text sensitive data in logs: It is prohibited to record plain text sensitive data (such as oral
    command, session ID jsessionid, etc.) to prevent the leakage of sensitive information.
    6. Disable caching of Web pages containing sensitive data: Web pages containing sensitive data should be prohibited from caching.
    storage to prevent the leakage of sensitive information or the exchange of user data through proxy servers.
    7. Perform strict permission authentication for sensitive data or page request interfaces that must be sent
requests:
- matchers:
  - type: word
    condition: or
    part: header
    words:
    - octet-stream
    - text/plain
  - type: regex
    part: body
    regex:
    - '[[0-9]{2}-[a-zA-Z]{3}-[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2} [A-Z]{3}] PHP'
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/debug.log'
  method: GET
