id: wp-gtranslate-open-redirect
info:
  name: GTranslate < 2.8.11 - Unauthenticated Open Redirect
  author:
  - l0ne1y
  description: |-
    WordPress Plugin GTranslate has URL redirection vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an open source application plug-in for WordPress.

    WordPress GTranslate version 2.8.11 and previous versions of gtranslate.php have an input validation error vulnerability, causing users to be redirected to a URL address that it did not validate before.
  severity: medium
  remediation: |-
    Official fix::
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/zh-cn/install-plugins/
    Temporary fix:
    1. The code fixes the jump address and does not allow users to control variables.
    2. The redirect target address adopts a whitelist mapping mechanism and only redirects to legal URLs.
    3. Verify the target address of the jump reasonably and fully, and inform the user of the risk of jump if it is not your own address.
requests:
- matchers:
  - type: word
    part: header
    words:
    - 'Location: www.pluginvulnerabilities.com'
  - type: status
    status:
    - 301
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/gtranslate/url_addon/gtranslate.php?glang=en&gurl=/www.pluginvulnerabilities.com'
  method: GET
