id: wp-install
info:
  name: WordPress Exposed Installation
  author:
  - l0ne1y
  description: |-
    Wordpress install installation file is not deleted vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.

    WordPress has lax access control, which allows attackers to access install.php and then reinstall CMS to gain control of the website.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com
    Temporary fix:
    1. Configure all security mechanisms
    2. Minimum principle, turn off or limit unused services
    3. Change default account information
    4. Use logs and alerts
    5. The echo information does not display any information related to the actual error.
    6. Check and repair security configuration items
requests:
- matchers:
  - type: word
    condition: and
    words:
    - <title>WordPress &rsaquo; Installation</title>
    - Site Title
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-admin/install.php'
  method: GET
