id: zhiyuan-file-upload
info:
  name: Zhiyuan OA Arbitrary File Upload Vulnerability
  author:
  - gy741
  tags:
  - zhiyuan
  - rce
  - upload
  description: |-
    Seeyon OA ajax.do Arbitrary File Upload Vulnerability
    Due to unauthorized access to certain interfaces in older Seeyon OA versions and insufficient filtering in some functions, attackers can craft malicious requests to upload malicious script files without logging in, thereby taking control of the server.
  reference:
  - https://www.programmersought.com/article/92658169875/
  severity: critical
  remediation: |-
    #### Official remediation:
    Upgrade the system to a version without the vulnerability, or download the security patch from the official website. Seeyon has released a patch for this vulnerability. Given its high severity, users are advised to apply the patch as soon as possible.
requests:
- matchers:
  - type: word
    words:
    - java.lang.NullPointerException:null
  - type: word
    part: header
    words:
    - text/html
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/seeyon/thirdpartyController.do.css/..;/ajax.do'
  method: GET
