id: Jcms-Ldap-SecretKeyLeak
info:
  name: Hanweb network-wide LDAP secret key leak
  author:
  - l0ne1y
  description: |-
    Hanweb JCMS LDAP secret key leak vulnerability.
    Hanweb JCMS is a content management system designed on a J2EE architecture. The system provides all the functions needed throughout the information lifecycle, including content collection, creation, management, delivery, publishing, and shared distribution.

    Hanweb JCMS has an LDAP secret-key leak vulnerability. An attacker can obtain the LDAP secret key to communicate with the server and thereby perform operations such as changing the administrator password.
  severity: critical
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    https://www.hanweb.com/

    Temporary Fix:
    1. Remove sensitive information involved in pages, or delete the pages that leak information.
    2. Store sensitive information encrypted; do not send it to the frontend unless necessary.
    3. Transmit sensitive information encrypted, and mask it if necessary.
    4. Validate user input on both the frontend and backend, using a dual validation mechanism.
    5. Verify that the user has permission to call a feature before invoking it.
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"<ldap>") && contains(body,"<enckey>")
  matchers-condition: and
  path:
  - '{{BaseURL}}/jcms/interface/ldap/ldapconf.xml'
  method: GET
