id: JCMS-Que_Model_JSP-Unauth
info:
  name: Hanweb JCMS que_model.jsp unauthorized access
  author:
  - l0ne1y
  description: |-
    Hanweb JCMS que_model.jsp privilege escalation / unauthorized access vulnerability.
    Hanweb JCMS is a content management system designed on a J2EE architecture. The system provides all the functions needed throughout the information lifecycle, including content collection, creation, management, delivery, publishing, and shared distribution.

    Hanweb JCMS has a privilege-escalation/unauthorized-access vulnerability. An attacker can exploit it to obtain system information.
  severity: medium
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    https://www.hanweb.com/

    Temporary Fix:
    1. Validate user input on both the frontend and backend, using a dual validation mechanism.
    2. Verify that the user has permission to call a feature before invoking it.
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"function doOptInterface")
  matchers-condition: and
  path:
  - '{{BaseURL}}/jcms/workflow/design/que_model.jsp?userid='
  method: GET
