id: VC-VerifyCodeServlet-Unauth
info:
  name: Hanweb full-system VerifyCodeServlet unauthorized access detection
  author:
  - l0ne1y
  description: |-
    Hanweb full-system VerifyCodeServlet backend bypass vulnerability.
    Hanweb is a software developer and technical service provider focused on “Internet + government services” and “digital government” construction in the e-government field.


    Hanweb jcms, jact, jsearch, vipchat, vc, xxgk, and other systems have an admin backend privilege bypass vulnerability.
  severity: high
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    https://www.hanweb.com/

    Temporary Fix:
    1. Validate user input on both the frontend and backend, using a dual validation mechanism.
    2. Verify that the user has permission to call a feature before invoking it.
    3. Enforce strict permission validation on administrative function modules. If not necessary, it is recommended not to expose them to the Internet or to apply network-layer access control.
requests:
- matchers:
  - type: word
    condition: and
    words:
    - Licence文件
    - 应用环境配置
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/vipchat/setup/opr_licenceinfo.jsp'
  - '{{BaseURL}}/jcms/setup/opr_licenceinfo.jsp'
  - '{{BaseURL}}/jsearch/setup/opr_licenceinfo.jsp'
  - '{{BaseURL}}/jact/setup/opr_licenceinfo.jsp'
  - '{{BaseURL}}/vc/setup/opr_licenceinfo.jsp'
  - '{{BaseURL}}/xxgk/setup/opr_licenceinfo.jsp'
  - '{{BaseURL}}/vipchat/setup/setup/admin.jsp'
  - '{{BaseURL}}/jcms/setup/setup/admin.jsp'
  - '{{BaseURL}}/jsearch/setup/setup/admin.jsp'
  - '{{BaseURL}}/jact/setup/setup/admin.jsp'
  - '{{BaseURL}}/vc/setup/setup/admin.jsp'
  - '{{BaseURL}}/xxgk/setup/setup/admin.jsp'
  method: GET
