id: joomla-manifest-file
info:
  name: Joomla Manifest File Disclosure
  author:
  - l0ne1y
  description: |-
    Joomla Manifest file information leaked
    By publishing a Joomla Manifest file that leaks Joomla installation information, such as version, file, and path
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program:
    http://www.joomla.org/
    Temporary fix:
    1. Prohibit the display of web pages containing sensitive data to prevent the leakage of sensitive information.
    2. Conduct strict permission authentication for sensitive data or page request interfaces that must be sent.
requests:
- matchers:
  - type: word
    condition: and
    words:
    - admin@joomla.org
    - www.joomla.org
  - type: word
    part: header
    words:
    - application/xml
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/administrator/manifests/files/joomla.xml'
  method: GET
