id: joomla-file-listing
info:
  name: Joomla! Database File List
  author:
  - l0ne1y
  description: |-
    Joomla database directory leaked
    The Joomla database directory /libraries/joomla/ Database / is leaked, and directory indexing has been enabled. Unauthorized access may lead to the disclosure of sensitive information.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program:
    http://www.joomla.org/
    Temporary fix:
    1. Prohibit the display of web pages containing sensitive data to prevent the leakage of sensitive information.
    2. Conduct strict permission authentication for sensitive data or page request interfaces that must be sent.
    3. Close the directory index on the /libraries/joomla/database/ directory, or delete the content from the web root directory. If the database can be downloaded, rotate any credentials contained in the database
requests:
- matchers:
  - type: word
    condition: and
    words:
    - Index of /libraries/joomla/database
    - Parent Directory
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/libraries/joomla/database/'
  method: GET
