id: joomla-config-dist-file
info:
  name: Joomla Config Dist File
  author:
  - l0ne1y
  description: |-
    joomla configuration file leaked
    php-dist is a file created by Joomla to save Joomla settings. Unauthorized access may lead to the leakage of sensitive information.
  severity: low
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program:
    http://www.joomla.org/
    Temporary fix:
    1. Prohibit the display of web pages containing sensitive data to prevent the leakage of sensitive information.
    2. Conduct strict permission authentication for sensitive data or page request interfaces that must be sent.
requests:
- matchers:
  - type: word
    condition: and
    words:
    - Joomla
    - JConfig
    - '@package'
  - type: word
    part: header
    words:
    - text/plain
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/configuration.php-dist'
  method: GET
