id: Joomla-Database-download
info:
  name: Joomla Database download vulnerability
  author:
  - 折跃
  description: |-
    Joomla! Database SQL file download
    Joomla! is an open source content management system (CMS).

    Joomla! has a database SQL file download vulnerability. Attackers can download SQL files to cause information leakage
  severity: high
  remediation: |-
    Official fix:
    1. Currently, the manufacturer has released an upgrade patch to fix the vulnerability. The link to obtain the patch is:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program:

    Temporary fix:
    1. Remove sensitive information from SQL files or delete SQL files
    2. Restrict access to SQL files
requests:
- matchers:
  - type: dsl
    condition: or
    dsl:
    - contains(body,'CREATE TABLE')
    - contains(body,'ALTER TABLE')
    - contains(body,'INSERT INTO')
    - contains(body,'CREATE')
  path:
  - '{{BaseURL}}/{{dbfile}}'
  attack: batteringram
  method: GET
  payloads:
    dbfile:
    - vicentecorpus/administrator/components/com_acymailing/tables.sql
    - administrator/components/com_admin/sql/updates/mysql/3.0.0.sql
    - administrator/components/com_djimageslider/sql/updates/2.0.sql
    - administrator/components/com_eventbooking/sql/config.eventbooking.sql
    - administrator/components/com_finder/sql/install.mysql.sql
    - administrator/components/com_kunena/install/sql/migrate/mysql/kunena.sql
    - administrator/components/com_jce/sql/mysql.sql
    - administrator/components/com_macgallery/install.sql
    - administrator/components/com_youtubegallery/sql/install.mysql.utf8.sql
    - dump.sql
  headers:
    Host: '{{Hostname}}'
  req-condition: true
  stop-at-first-match: true
variables:
  verify: '{{rand_text_alphanumeric(32,"")}}'
