id: CNVD-2021-15824
info:
  name: EmpireCMS DOM Cross Site-Scripting
  author:
  - l0ne1y
  description: |
    EmpireCMS has an XSS vulnerability

    EmpireCMS is a content management system (CMS).

    EmpireCMS has an XSS vulnerability. Attackers can exploit it to obtain sensitive information such as user cookies.
  severity: medium
  remediation: "Official remedy:<br />1. Upgrade the system to a non-vulnerable version, or download the security patch from the official website\nhttp://www.phome.net/ \n\nTemporary remedy:<br
    />1. Filter inputs (and URL parameters), encode outputs, and combine whitelisting and blacklisting. That is, filter all submitted content and the parameters in the URL, filtering out content that could cause script execution; then html-encode the content dynamically output to the page so the script cannot execute in the browser. Although input filtering can be bypassed, it still blocks a large part of XSS attacks; finally, restrict characters using whitelist or blacklist.'"
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - if(Request("url")!=0)
    - href=\""+Request("url")+"\"
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/e/ViewImg/index.html?url=javascript:alert(1)'
  method: GET
