id: Metinfo-login_check-SQLi
info:
  name: MetInfoCMS login_check.php SQL injection vulnerability detection
  author:
  - l0ne1y
  description: |-
    MetInfoCMS login_check.php SQL injection vulnerability.
    MetInfo is an open-source, free CMS building system suitable for enterprise websites. The MetInfo enterprise website management system is mainly used to build enterprise websites and uses a PHP+Mysql architecture.

    In MetinfoCMS, the login_check.php page has an SQL injection vulnerability. An attacker can exploit it to obtain sensitive information.
  reference:
  - http://www.wooyun.org/bugs/wooyun-2015-0106582
  severity: critical
  remediation: |2-

    Remediation
    Official Fix:
    1. Upgrade to a non-vulnerable version of the system, or download the security patch from the official site
    https://www.mituo.cn/
    Temporary Fix:
    1. Use prepared statements. When using PDO, be careful not to concatenate variables directly into PDO statements. All queries should use the parameterized query interface provided by the database; parameterized statements use parameters instead of embedding user-input variables into SQL statements. Virtually all database systems provide a parameterized SQL execution interface, which can very effectively prevent SQL injection attacks.
    2. Escape special characters (such as '"<>&*;) entering the database, or perform encoding conversion.
    3. Validate the type of each piece of data; for example, numeric data must be numeric and the corresponding database field must be of type int.
    4. Strictly enforce data length limits, which to some degree prevents long SQL injection statements from executing correctly.
    5. Use consistent encoding across every data layer of the website; UTF-8 is recommended. Inconsistent encoding between layers may allow some filtering mechanisms to be bypassed.
    6. Strictly limit the database privileges of the website user, granting only the privileges needed to perform their work, thereby minimizing the damage injection attacks can cause to the database.
    7. Avoid displaying SQL error messages, such as type errors or field mismatches, to prevent attackers from using such error information for reconnaissance.
    8. Filter dangerous characters; for example, use regular expressions to match keywords such as union, sleep, and, select, and load_file, and stop execution if matched.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - 'status_code_1==200 && status_code_2==200 '
    - '!contains(body_1,"not have this language") && contains(body_2,"not have this
      language")'
  matchers-condition: and
  path:
  - '{{BaseURL}}/admin/login/login_check.php?langset=cn%27%20and%20%271%27%20%3D%271'
  - '{{BaseURL}}/admin/login/login_check.php?langset=cn%27%20and%20%271%27%20%3D%272'
  method: GET
