id: Metinfo-V6_1_0-phpinfo
info:
  name: Metinfo v6.1.0 phpinfo.php sensitive information disclosure
  author:
  - l0ne1y
  description: |-
    Metinfo v6.1.0 phpinfo.php sensitive information disclosure.
    MetInfo is an enterprise website management system based on a PHP Mysql architecture.
    The MetInfo system has a phpinfo information disclosure. An attacker can exploit it to obtain sensitive information.
  severity: low
  remediation: |-
    Official Fix:
    MetInfo recommends that users upgrade to the latest version and download it for use:
    http://www.metinfo.cn/
    Temporary Fix:<br/>1. Remove sensitive information involved in pages, cookies, or caches, or delete the pages that leak information.<br/>2. Store sensitive information encrypted; do not send it to the frontend unless necessary.<br/>3. Send sensitive information encrypted, and mask it if necessary.<br/>4. Do not use self-developed encryption algorithms; use public, secure standard encryption algorithms.<br/>5. Do not record plaintext sensitive data in logs (such as passwords or session identifiers like jsessionid), to prevent sensitive information leakage.<br/>6. Disable caching of web pages containing sensitive data. All pages with sensitive data should be non-cacheable, to prevent sensitive information leakage or cross-user data issues for users behind proxy servers.<br/>7. Enforce strict permission authentication for sensitive data that must be sent or for page request interfaces.
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"bin/sh")
  matchers-condition: and
  path:
  - '{{BaseURL}}/install/phpinfo.php'
  method: GET
