id: Discuz-WechatPlugins-Unauth
info:
  name: Discuz Wechat Plugins Unauth
  author:
  - l0ne1y
  description: |-
    Discuz! WeChat plugin unauthorized login vulnerability.
    Discuz! is a generic community forum software system.

    Discuz! has an unauthorized-access vulnerability. Such vulnerabilities include horizontal privilege escalation, vertical privilege escalation, and unauthorized access. In web programs, improper permission control allows users to access or operate on data they are not authorized to access, i.e., unauthorized access.
  severity: high
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. Validate user input on both the frontend and backend, using a dual validation mechanism.
    2. Verify that the user has permission to call a feature before invoking it.
    3. Use encrypted resource IDs for direct object references to prevent attackers from enumerating IDs, and apply special handling to sensitive data.
requests:
- matchers:
  - type: word
    condition: and
    part: header
    words:
    - set-cookie
    - auth
    - location
    - wsq.discuz.com
  - type: status
    status:
    - 302
  matchers-condition: and
  path:
  - '{{BaseURL}}/plugin.php?id=wechat:wechat&ac=wxregister'
  method: GET
