id: discuz-info-admincp
info:
  name: Discuz 7.2 website path disclosure vulnerability
  author:
  - 折跃
  description: |-
    Discuz! 7.2 physical path disclosure vulnerability.
    Discuz! is a generic community forum software system.

    Discuz! 7.2 has a physical path disclosure vulnerability.
  severity: low
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. Suppress the output of error messages.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,'/manyou/admincp.php')
    - '!contains(body,''/manyou/admincp.php?my_suffix=%0A%0DTOBY57'')'
  path:
  - '{{BaseURL}}/manyou/admincp.php?my_suffix=%0A%0DTOBY57'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
