id: discuz-info-config_ucenter
info:
  name: Discuz config_ucenter.php backup file vulnerability
  author:
  - 折跃
  description: |-
    Discuz! backup file disclosure vulnerability.
    Discuz! is a generic community forum software system.

    Discuz! has a backup file disclosure vulnerability. An attacker can download backup files to obtain sensitive system information.
  severity: high
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. Remove sensitive information involved in pages, or delete the pages that leak the information.
    2. Store sensitive information encrypted; do not send it to the frontend unless necessary.
    3. Transmit sensitive information encrypted, and mask it if necessary.
    4. Prevent external users from accessing files with suffixes such as .bak.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,'<?php')
  path:
  - '{{BaseURL}}/config/config_ucenter.php.bak'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
