id: Discuz-unauthorized-tools
info:
  name: Discuz! X3 first-aid kit unauthorized access vulnerability
  author:
  - 折跃
  description: |-
    Discuz! X3 tools.php unauthorized access vulnerability.
    Discuz! is a generic community forum software system.

    Discuz! X3 first-aid kit tools.php has an unauthorized access vulnerability.
  severity: high
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. Validate user input on both the frontend and backend, using a dual validation mechanism.
    2. Verify that the user has permission to call a feature before invoking it.
    3. Disable the first-aid kit page.
    4. Change the first-aid kit default password to a strong one.
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,'?action=setadmin')
    - contains(body,'tools.php?action=login')
    - contains(body,'toolpassword')
  path:
  - '{{BaseURL}}/source/plugin/tools/tools.php'
  method: GET
  headers:
    Host: '{{Hostname}}'
  req-condition: true
