id: huawei-HG532e-default-login
info:
  name: Huawei HG532e Default Credential
  author:
  - l0ne1y
  description: |-
    Huawei HG532e default account and password
    Huawei HG532e is a wireless router product of Huawei Technologies Co., Ltd., China.
    The web management console of the Huawei HG532e has a default account.
  severity: high
  remediation: |-
    1. Configure all security mechanisms.
    2. Apply the principle of least privilege; disable or restrict unused services.
    3. Change the default account information.
    4. Use logging and alerts.
    5. Do not display any information related to actual errors in responses.
    6. Check and fix security configuration items.
requests:
- matchers:
  - type: word
    part: header
    words:
    - 'Set-Cookie: SessionID'
  - type: word
    part: body
    words:
    - <title>replace</title>
  - type: status
    status:
    - 200
  matchers-condition: and
  raw:
  - |
    POST /index/login.cgi HTTP/1.1
    Host: {{Hostname}}
    Cookie: Language=en; FirstMenu=Admin_0; SecondMenu=Admin_0_0; ThirdMenu=Admin_0_0_0
    Content-Type: application/x-www-form-urlencoded

    Username=user&Password=MDRmODk5NmRhNzYzYjdhOTY5YjEwMjhlZTMwMDc1NjllYWYzYTYzNTQ4NmRkYWIyMTFkNTEyYzg1YjlkZjhmYg%3D%3D
